import { test, expect } from '@playwright/test';
test('mobile registration, persisted login, credits, logout, and preview navigation', async ({page}) => {
  const errors=[];page.on('pageerror',error=>errors.push(error.message));
  const username=`preview_${Date.now().toString(36)}`;
  await page.goto('/');
  await expect(page.getByRole('heading',{name:'Explore materials',exact:true})).toBeVisible();
  await expect(page.getByRole('heading',{name:'Good materials. New beginnings.'})).toHaveCount(0);
  await expect(page.getByRole('heading',{name:'Recently Added'})).toBeVisible();
  await expect(page.getByRole('link',{name:/Foam board offcuts/}).first()).toBeVisible();
  await page.screenshot({path:'test-results/explore-mobile.png',fullPage:true});
  await page.getByRole('navigation',{name:'Main navigation'}).getByRole('link',{name:'Profile'}).click();
  await page.getByRole('link',{name:'Create account',exact:true}).click();
  await page.getByLabel('Username',{exact:true}).fill(username);
  await page.getByLabel('Password',{exact:true}).fill('Local-demo-2026!');
  await page.getByRole('button',{name:'Create account',exact:true}).click();
  await expect(page.getByRole('heading',{name:username,exact:true})).toBeVisible();
  await expect(page.getByRole('link',{name:'2 credits',exact:true})).toBeVisible();
  await page.reload();
  await expect(page.getByRole('heading',{name:username,exact:true})).toBeVisible();
  await page.getByRole('link',{name:'Credit history',exact:true}).click();
  await expect(page.getByText('Welcome credits',{exact:true})).toHaveCount(1);
  await expect(page.getByText('+2',{exact:true})).toBeVisible();
  await page.screenshot({path:'test-results/credits-mobile.png',fullPage:true});
  await page.getByRole('navigation').getByRole('link',{name:'Profile'}).click();
  await page.screenshot({path:'test-results/profile-mobile.png',fullPage:true});
  await page.getByRole('button',{name:'Log out',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Welcome back'})).toBeVisible();
  await page.getByLabel('Username',{exact:true}).fill(username);
  await page.getByLabel('Password',{exact:true}).fill('wrong-password');
  await page.getByRole('button',{name:'Log in',exact:true}).click();
  await expect(page.getByRole('alert')).toContainText('Invalid username or password.');
  await page.getByLabel('Password',{exact:true}).fill('Local-demo-2026!');
  await page.getByRole('button',{name:'Log in',exact:true}).click();
  await expect(page.getByRole('heading',{name:username,exact:true})).toBeVisible();
  await page.getByRole('navigation').getByRole('link',{name:'Share Material'}).click();
  await expect(page.getByRole('heading',{name:'Share Material',exact:true})).toBeVisible();
  await page.getByRole('navigation').getByRole('link',{name:'Explore',exact:true}).click();
  await page.getByRole('textbox',{name:'Search materials'}).fill('canvas');
  await page.getByRole('button',{name:'Submit search'}).click();
  await expect(page.getByRole('heading',{name:'Cotton canvas'})).toHaveCount(1);
  await page.getByRole('link',{name:/Cotton canvas/}).click();
  await expect(page.getByRole('heading',{name:'Cotton canvas'})).toBeVisible();
  await expect(page.getByText('1 credit per reservation')).toBeVisible();
  await page.setViewportSize({width:320,height:740});
  await page.goto('/');
  await expect(page.getByRole('heading',{name:'Recently Added'})).toBeVisible();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({path:'test-results/explore-320.png',fullPage:true});
  await page.setViewportSize({width:1440,height:1000});await page.reload();
  await expect(page.getByRole('heading',{name:'Recently Added'})).toBeVisible();
  await page.screenshot({path:'test-results/explore-desktop.png',fullPage:true});
  expect(errors).toEqual([]);
  console.log(`Verified browser account: ${username}; balance: 2 credits; one welcome entry.`);
});
