import { test, expect } from '@playwright/test';
import sharp from 'sharp';
import { cameraFixture } from './camera-fixture.mjs';

const video=await cameraFixture();
const image=await sharp({create:{width:240,height:180,channels:3,background:'#b0c68a'}}).png().toBuffer();
test.use({permissions:['camera'],launchOptions:{args:['--use-fake-device-for-media-stream',`--use-file-for-fake-video-capture=${video}`]}});
async function register(request,prefix){const username=`${prefix}_${Date.now().toString(36)}`;expect((await request.post('/api/auth/register',{data:{username,password:'fulfillment-test'}})).status()).toBe(201);return username;}
async function setup(page){
  const owner=await register(page.request,'f_owner');const upload=async()=>{const r=await page.request.post('/api/uploads',{headers:{'Content-Type':'image/png','X-File-Name':'foam.png'},data:image});return(await r.json()).photo.id;};
  const photo=await upload(),placement=await upload();const saved=await page.request.post('/api/deposits',{data:{request_key:crypto.randomUUID(),name:'Pickup foam',category_id:1,quantity:2,unit:'sheets',dimensions_spec:'A3, 5 mm',condition:'Good',color:'White',photo_ids:[photo]}});const d=(await saved.json()).deposit;
  for(const [path,data] of [['arrive',{}],['verify-zone',{qr:'REMATERIAL|ZONE|BOARD_FOAM'}],['placement',{photo_ids:[placement]}],['confirm',{}]])expect((await page.request.post(`/api/deposits/${d.id}/${path}`,{data})).status()).toBe(200);
  await page.request.post('/api/auth/logout',{data:{}});const collector=await register(page.request,'f_taker');const reserved=await page.request.post(`/api/materials/${d.material_id}/reserve`,{data:{quantity:1,request_key:crypto.randomUUID()}});const r=(await reserved.json()).reservation;return{d,r,owner,collector};
}
async function scan(page){await page.getByRole('button',{name:'I’m at the Hub',exact:true}).click();await expect(page.getByRole('heading',{name:'Find area',exact:true})).toBeVisible();await expect(page.locator('input')).toHaveCount(0);await expect(page.getByRole('button',{name:/Can’t scan/})).toHaveCount(0);await expect(page.getByRole('alert')).toContainText(/This is the Wood zone\. Your material (is in|goes back to) Board & Foam\./,{timeout:15000});}
async function login(page,username){await page.request.post('/api/auth/logout',{data:{}});await page.goto('/login');await page.getByLabel('Username',{exact:true}).fill(username);await page.getByLabel('Password',{exact:true}).fill('fulfillment-test');await page.getByRole('button',{name:'Log in',exact:true}).click();await expect(page.getByRole('heading',{name:username,exact:true})).toBeVisible();}

test('B pickup in three steps with the label code, persistence and camera return with fresh photos',async({page})=>{
  test.setTimeout(90000);const errors=[];page.on('pageerror',e=>errors.push(e.message));const{d,r,owner,collector}=await setup(page);
  await page.goto('/me');await page.getByRole('link',{name:'My Reservations',exact:true}).click();await page.locator('.reservation-card .active-task').click();await page.getByRole('link',{name:'Start pickup'}).click();
  await expect(page.getByRole('heading',{name:'Go to the Hub',exact:true})).toBeVisible();await expect(page.getByText('Building 17 · L1',{exact:true})).toBeVisible();await expect(page.getByLabel('Illustration of the Board & Foam zone sign')).toBeVisible();
  await expect(page.getByAltText('Material placement')).toHaveCount(0);await expect(page.getByText(/coming soon|to be confirmed/i)).toHaveCount(0);await expect(page.locator('.page-heading h2')).toHaveCount(0);
  await page.locator('.strip-toggle').click();await expect(page.locator('.material-strip-details')).toContainText('Reserved1 sheet');await expect(page.locator('.material-strip-details')).toContainText('ColorWhite');await expect(page.locator('.material-strip .icon-button[aria-label="Edit material information"]')).toHaveCount(0);
  await page.screenshot({path:'test-results/pickup-guide-402.png',fullPage:true});
  await scan(page);await expect(page.getByAltText('Material placement')).toBeVisible();let data=(await(await page.request.get(`/api/reservations/${r.id}`)).json()).reservation;expect(data.status).toBe('reserved');expect(data.stock_quantity).toBe(2);expect((await(await page.request.get('/api/auth/me')).json()).user.held).toBe(1);
  await expect(page.getByRole('heading',{name:'Pick up',exact:true})).toBeVisible({timeout:25000});await expect(page.getByAltText('Material placement')).toBeVisible();await expect(page.locator('.find-label')).toContainText(`Find the label ${d.display_code}`);await expect(page.getByRole('button',{name:'Confirm pickup'})).toBeDisabled();
  await page.getByLabel('Material code on the label').fill('m999999');await page.getByRole('button',{name:'Confirm pickup'}).click();await expect(page.getByRole('alert')).toContainText('does not match');await expect(page.getByRole('heading',{name:'Pick up',exact:true})).toBeVisible();await expect(page.getByRole('link',{name:'Missing or doesn’t match? Report a problem'})).toBeVisible();
  for(const width of [320,402,1440]){await page.setViewportSize({width,height:874});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`test-results/pick-up-${width}.png`,fullPage:true});}
  await page.setViewportSize({width:402,height:874});await page.getByLabel('Material code on the label').fill(d.display_code.toLowerCase());await expect(page.getByLabel('Material code on the label')).toHaveValue(d.display_code);await page.getByRole('button',{name:'Confirm pickup'}).evaluate(el=>{el.click();el.click();});
  await expect(page.getByRole('heading',{name:'Enjoy your material'})).toBeVisible();await expect(page.locator('.success-credit')).toHaveText('1 credit usedYou have 1 credit left');await expect(page.locator('.back-link')).toHaveCount(0);await expect(page.getByText(/reservation hold|remaining ·/)).toHaveCount(0);
  await page.reload();await expect(page.getByRole('heading',{name:'Enjoy your material'})).toBeVisible();await expect(page.getByRole('link',{name:'My reservations'})).toBeVisible();await page.getByRole('link',{name:'Done',exact:true}).click();await expect(page.getByRole('heading',{name:'New on the shelf'})).toBeVisible();
  const collected=(await(await page.request.get('/api/reservations/'+r.id)).json()).reservation;
  expect(collected.status).toBe('collected');expect(collected.stock_quantity).toBe(1);
  const afterPickup=(await(await page.request.get('/api/auth/me')).json()).user;expect(afterPickup.balance).toBe(1);expect(afterPickup.held).toBe(0);
  expect((await page.request.post('/api/reservations/'+r.id+'/pickup',{data:{material_code:d.display_code,matches:true}})).status()).toBe(200);
  expect((await(await page.request.get('/api/reservations/'+r.id)).json()).reservation.stock_quantity).toBe(1);
  expect((await(await page.request.get('/api/auth/me')).json()).user.balance).toBe(1);
  await login(page,owner);await page.getByRole('link',{name:'My Posts',exact:true}).click();await expect(page.locator('.post-list')).toContainText('1 sheet collected, 1 remaining');
  await login(page,collector);await page.goto(`/reservations/${r.id}`);await expect(page.locator('.status-badge')).toHaveText('Collected');expect((await(await page.request.get('/api/reservations/'+r.id)).json()).reservation.completed_at).toBe(collected.completed_at);await page.getByRole('link',{name:'Return Material',exact:true}).click();await expect(page.getByRole('heading',{name:'Return Guide'})).toBeVisible();await scan(page);await expect(page.getByRole('heading',{name:'Return Material',exact:true})).toBeVisible({timeout:25000});await expect(page.getByRole('button',{name:'Confirm return'})).toBeDisabled();
  await page.getByLabel('Return placement photos from gallery').setInputFiles({name:'returned.png',mimeType:'image/png',buffer:image});await expect(page.getByAltText('Return placement photos 1')).toBeVisible();await expect(page.getByText('Saving photos…',{exact:true})).toHaveCount(0);await page.reload();await expect(page.getByAltText('Return placement photos 1')).toBeVisible();const returnURL=page.url();const savedReturn=(await(await page.request.get('/api/reservations/'+r.id)).json()).reservation.return;await login(page,collector);await page.goto(returnURL);await expect(page.getByAltText('Return placement photos 1')).toBeVisible();expect((await(await page.request.get('/api/reservations/'+r.id)).json()).reservation.return).toEqual(savedReturn);await page.getByRole('checkbox').check();await expect(page.getByRole('button',{name:'Confirm return'})).toBeEnabled();await page.screenshot({path:'test-results/return-material-402.png',fullPage:true});await page.getByRole('button',{name:'Confirm return'}).evaluate(el=>{el.click();el.click();});await expect(page.getByRole('heading',{name:'My Reservations'})).toBeVisible();await expect(page.locator('.status-badge')).toHaveText('Returned');await expect.poll(async()=>(await(await page.request.get('/api/auth/me')).json()).user.available).toBe(2);await page.reload();await expect(page.locator('.status-badge')).toHaveText('Returned');
  expect((await page.request.post('/api/reservations/'+r.id+'/return/confirm',{data:{placed:true}})).status()).toBe(200);expect((await(await page.request.get('/api/auth/me')).json()).user.balance).toBe(2);
  data=(await(await page.request.get(`/api/materials/${d.material_id}`)).json()).material;expect(data.stock_quantity).toBe(2);expect(data.status).toBe('available');await login(page,collector);await page.goto(`/reservations/${r.id}`);await expect(page.locator('.status-badge')).toHaveText('Returned');await expect(page.getByRole('link',{name:'Return Material'})).toHaveCount(0);expect(errors).toEqual([]);
});

test('B report from Pick up restores credit and shows provider Needs Review',async({page})=>{
  test.setTimeout(60000);const{d,r,owner,collector}=await setup(page);await page.goto(`/reservations/${r.id}/guide`);await scan(page);await expect(page.getByRole('heading',{name:'Pick up',exact:true})).toBeVisible({timeout:25000});await page.getByRole('link',{name:'Missing or doesn’t match? Report a problem'}).click();await page.getByLabel('Reason',{exact:true}).selectOption('Other');await expect(page.getByRole('button',{name:'Submit report'})).toBeDisabled();await page.getByLabel('Description (required)').fill('Label and thickness do not match.');await page.getByLabel('Problem photos from gallery').setInputFiles({name:'problem.png',mimeType:'image/png',buffer:image});await expect(page.getByRole('button',{name:'Submit report'})).toBeEnabled();await page.screenshot({path:'test-results/problem-report-402.png',fullPage:true});await page.getByRole('button',{name:'Submit report'}).click();await expect(page.getByRole('heading',{name:'My Reservations'})).toBeVisible();await expect(page.locator('.status-badge')).toHaveText('Issue Reported');await expect(page.getByText('Issue reported. Open, needs review',{exact:true})).toBeVisible();await expect.poll(async()=>(await(await page.request.get('/api/auth/me')).json()).user.available).toBe(2);await page.reload();await expect(page.locator('.status-badge')).toHaveText('Issue Reported');
  await page.goto(`/materials?q=${d.display_code}`);await expect(page.getByText('No materials found',{exact:true})).toBeVisible();await login(page,owner);await page.getByRole('link',{name:'My Posts',exact:true}).click();await expect(page.locator('.post-list')).toContainText('Needs Review');await expect(page.locator('.post-list')).toContainText('Reported: Other');await page.locator('.post-list .active-task').click();await expect(page.getByText('Label and thickness do not match.',{exact:true})).toBeVisible();await expect(page.getByAltText('Reported problem')).toBeVisible();await page.screenshot({path:'test-results/provider-needs-review-402.png',fullPage:true});
  await login(page,collector);await page.goto(`/reservations/${r.id}`);await expect(page.locator('.status-badge')).toHaveText('Issue Reported');
});

test('B camera denied explains it and offers retry without a manual zone field',async({page})=>{
  const{r}=await setup(page);await page.addInitScript(()=>{navigator.mediaDevices.getUserMedia=()=>Promise.reject(new DOMException('Denied','NotAllowedError'));});await page.goto(`/reservations/${r.id}/guide`);await page.getByRole('button',{name:'I’m at the Hub',exact:true}).click();
  await expect(page.getByRole('alert')).toContainText('Camera permission was denied');await expect(page.getByRole('button',{name:'Retry camera'})).toBeVisible();await expect(page.locator('input')).toHaveCount(0);
  expect((await(await page.request.get(`/api/reservations/${r.id}`)).json()).reservation.status).toBe('reserved');
});
