import { test, expect } from '@playwright/test';
import sharp from 'sharp';

const photo=await sharp({create:{width:120,height:90,channels:3,background:'#bbc996'}}).png().toBuffer();
async function register(request,prefix){const username=`${prefix}_${Date.now().toString(36)}`;expect((await request.post('/api/auth/register',{data:{username,password:'review-browser'}})).status()).toBe(201);return username;}
async function upload(request){return(await(await request.post('/api/uploads',{headers:{'Content-Type':'image/png','X-File-Name':'review.png'},data:photo})).json()).photo.id;}
async function login(page,username){await page.request.post('/api/auth/logout',{data:{}});await page.goto('/login');await page.getByLabel('Username',{exact:true}).fill(username);await page.getByLabel('Password',{exact:true}).fill('review-browser');await page.getByRole('button',{name:'Log in',exact:true}).click();await expect(page.getByRole('heading',{name:username,exact:true})).toBeVisible();}
async function setup(page){
  const owner=await register(page.request,'rv_owner'),image=await upload(page.request),placement=await upload(page.request);
  const d=(await(await page.request.post('/api/deposits',{data:{request_key:crypto.randomUUID(),name:'Review board',category_id:1,quantity:3,unit:'sheets',dimensions_spec:'A3',color:'White',condition:'Good',notes:'Initial notes',photo_ids:[image]}})).json()).deposit;
  for(const [path,data] of [['arrive',{}],['verify-zone',{qr:'REMATERIAL|ZONE|BOARD_FOAM'}],['placement',{photo_ids:[placement]}],['confirm',{}]])expect((await page.request.post(`/api/deposits/${d.id}/${path}`,{data})).status()).toBe(200);
  await page.request.post('/api/auth/logout',{data:{}});const reporter=await register(page.request,'rv_reporter');const reservation=(await(await page.request.post(`/api/materials/${d.material_id}/reserve`,{data:{quantity:1,request_key:crypto.randomUUID()}})).json()).reservation;
  await page.request.post(`/api/reservations/${reservation.id}/verify-zone`,{data:{qr:'REMATERIAL|ZONE|BOARD_FOAM'}});const problem=await upload(page.request);
  const r=(await(await page.request.post(`/api/reservations/${reservation.id}/issues`,{data:{reason:'Damaged',notes:'The corner has a crack.',photo_ids:[problem]}})).json()).reservation;
  return{owner,reporter,d,r,issue:r.issue};
}

test('auth pages hide only the global guest Log in and retain form actions and other headers',async({page})=>{
  for(const [url,button] of [['/login','Log in'],['/register','Create account']]){await page.goto(url);await expect(page.locator('.explore-heading').getByRole('link',{name:'Log in',exact:true})).toHaveCount(0);await expect(page.getByRole('button',{name:button,exact:true})).toBeVisible();await expect(page.getByRole('link',{name:'Explore materials',exact:true})).toBeVisible();}
  await page.goto('/');await expect(page.locator('.explore-heading').getByRole('link',{name:'Log in',exact:true})).toBeVisible();await register(page.request,'rv_header');await page.reload();await expect(page.locator('.explore-heading').getByRole('link',{name:'2 credits'})).toBeVisible();
});

test('publisher sees report in Profile and My Posts, relists with verified details, B sees result',async({page})=>{
  test.setTimeout(60000);const{owner,reporter,d,r,issue}=await setup(page);
  await page.goto(`/me/issues/${issue.id}`);await expect(page.getByRole('alert')).toContainText('Report not found');
  await login(page,owner);await expect(page.getByText('Action required',{exact:true})).toBeVisible();await expect(page.getByText('1 report pending review',{exact:true})).toBeVisible();await page.getByRole('link',{name:'My Posts',exact:true}).click();
  await expect(page.getByText('Action required',{exact:true})).toBeVisible();const card=page.locator('.post-list article');await expect(card).toContainText('Needs Review');await expect(card).toContainText('The corner has a crack.');await expect(card).toContainText('This material is temporarily hidden from Explore.');await expect(card.locator('time')).toBeVisible();await expect(card.getByAltText('Reported problem')).toBeVisible();await page.screenshot({path:'test-results/review-action-required-402.png',fullPage:true});
  await card.getByRole('link',{name:'Review and relist',exact:true}).click();await expect(page.getByRole('button',{name:'Confirm relist'})).toBeDisabled();await page.getByLabel('Available quantity (sheets)').fill('2');await page.getByLabel('Condition',{exact:true}).fill('Used');await page.getByLabel('Notes',{exact:true}).fill('Checked at Hub; usable after trimming.');await page.getByRole('button',{name:'Remove reviewed placement photos 1',exact:true}).click();await page.getByLabel('Reviewed placement photos from gallery').setInputFiles({name:'checked.png',mimeType:'image/png',buffer:photo});await expect(page.getByAltText('Reviewed placement photos 1')).toBeVisible();await page.getByRole('checkbox').check();await expect(page.getByRole('button',{name:'Confirm relist'})).toBeEnabled();await page.screenshot({path:'test-results/review-relist-402.png',fullPage:true});await page.getByRole('button',{name:'Confirm relist'}).evaluate(el=>{el.click();el.click();});await expect(page.getByRole('heading',{name:'Report resolved'})).toBeVisible();await expect(page.getByText('Issue resolved — relisted',{exact:true})).toBeVisible();await page.reload();await expect(page.getByText('Issue resolved — relisted',{exact:true})).toBeVisible();
  const resolved=(await(await page.request.get(`/api/me/issues/${issue.id}`)).json()).issue;const replay=await page.request.post(`/api/me/issues/${issue.id}/resolve`,{data:{resolution:'relisted',version:0}});expect(replay.status()).toBe(200);expect((await(await page.request.get('/api/auth/me')).json()).user.balance).toBe(3);
  await page.goto('/me');await expect(page.getByText('Action required',{exact:true})).toHaveCount(0);await page.goto(`/materials?q=${d.display_code}`);await expect(page.locator('.material-card')).toHaveCount(1);await page.locator('.material-card').click();await expect(page.locator('.specs').first()).toContainText('2 sheets');await expect(page.locator('.specs').first()).toContainText('Used');await expect(page.getByText('Checked at Hub; usable after trimming.',{exact:true})).toBeVisible();
  await login(page,reporter);await page.goto('/me/reservations');await expect(page.getByText('Issue resolved — relisted',{exact:true})).toBeVisible();await expect.poll(async()=>(await(await page.request.get('/api/auth/me')).json()).user.available).toBe(2);await page.reload();await expect(page.getByText('Issue resolved — relisted',{exact:true})).toBeVisible();expect(resolved.placement_photos).toHaveLength(1);expect((await(await page.request.get(`/api/reservations/${r.id}`)).json()).reservation.status).toBe('issue_reported');
});

test('publisher removal requires a second confirmation, remains archived and syncs B outcome',async({page})=>{
  const{owner,reporter,d,issue}=await setup(page);await login(page,owner);await page.getByRole('link',{name:'My Posts',exact:true}).click();await page.locator('.post-list article').getByRole('link',{name:'Remove material',exact:true}).click();await page.getByRole('button',{name:'Remove material',exact:true}).click();await expect(page.getByRole('group',{name:'Confirm removal'})).toBeVisible();await page.getByRole('button',{name:'Keep material',exact:true}).click();expect((await(await page.request.get(`/api/me/issues/${issue.id}`)).json()).issue.status).toBe('open');
  await page.getByRole('button',{name:'Remove material',exact:true}).click();await page.getByRole('button',{name:'Yes, remove material',exact:true}).evaluate(el=>{el.click();el.click();});await expect(page.getByText('Issue resolved — removed',{exact:true})).toBeVisible();await page.reload();await expect(page.getByRole('button',{name:'Confirm relist'})).toHaveCount(0);await expect(page.getByText('Issue resolved — removed',{exact:true})).toBeVisible();expect((await page.request.post(`/api/me/issues/${issue.id}/resolve`,{data:{resolution:'removed'}})).status()).toBe(200);
  await page.goto('/me/posts');await expect(page.locator('.post-list')).toContainText('Removed / Archived');await expect(page.getByText('Action required',{exact:true})).toHaveCount(0);await page.goto(`/materials?q=${d.display_code}&availability=all`);await expect(page.getByText('No materials found',{exact:true})).toBeVisible();await login(page,reporter);await page.goto('/me/reservations');await expect(page.getByText('Issue resolved — removed',{exact:true})).toBeVisible();await expect.poll(async()=>(await(await page.request.get('/api/auth/me')).json()).user.available).toBe(2);await page.screenshot({path:'test-results/review-removed-result-402.png',fullPage:true});
});
