import { useContext, useEffect, useRef, useState, type ChangeEvent, type FormEvent } from 'react';
import { Link, Navigate, useLocation, useNavigate, useParams } from 'react-router-dom';
import { ArrowLeft, ArrowRight, Camera, Check, CheckCircle2, ChevronRight, Clock3, ImagePlus, Leaf, MapPin, Package, Plus, Trash2 } from 'lucide-react';
import type { IScannerControls } from '@zxing/browser';
import { Auth, api, type User } from './lib';
import { ManagedPosts } from './post-management';
import { MaterialPhoto, CompletionSummary, StepBar, MaterialStrip, type FlowStep } from './ui';
import { Remaining, type Reservation } from './reservations';
import { ActionRequired, IssueDetails, type Issue } from './reviews';
import { useI18n, messageOf, validateForm, ApiError, type Message } from './i18n';

type Photo = {id:number;url:string};
type Deposit = {id:number;material_id:number;display_code:string;name:string;category_id:number;category:string;custom_category_name:string|null;initial_quantity:number;stock_quantity:number;unit:string;dimensions_spec:string;dimensions_not_applicable:number;color:string;condition:string;reference_url:string|null;notes:string;zone_id:number;zone:string;version:number;status:string;deposit_status:string;arrived_at:string|null;verified_zone_id:number|null;photos:Photo[];placement_photos:Photo[];collected_quantity:number;issues:Issue[]};
type FormData = {request_key:string;name:string;category_id:string;custom_category_name:string;quantity:string;unit:string;dimensions_spec:string;dimensions_not_applicable:boolean;color:string;condition:string;reference_url:string;notes:string;photo_ids:number[]};
const blank = ():FormData => ({request_key:crypto.randomUUID(),name:'',category_id:'',custom_category_name:'',quantity:'',unit:'',dimensions_spec:'',dimensions_not_applicable:false,color:'',condition:'',reference_url:'',notes:'',photo_ids:[]});
function ErrorMessage({error}:{error:Message}) { const {t,msg,language}=useI18n();  return error?<div className="notice" role="alert">{msg(error)}</div>:null; }
function useAccount() { const auth=useContext(Auth);const navigate=useNavigate();const location=useLocation();useEffect(()=>{if(!auth.loading&&!auth.user)navigate(`/login?next=${encodeURIComponent(location.pathname+location.search)}`,{replace:true});},[auth.loading,auth.user,location.pathname,location.search,navigate]);return auth; }
/** Where a pending deposit currently is: 2 = go to the Hub, 3 = find its zone (scan), 4 = drop off. */
function depositStage(d:Deposit){return d.verified_zone_id===d.zone_id?{step:4,label:'Drop off',to:`/deposits/${d.id}/place`}:d.arrived_at?{step:3,label:'Find area',to:`/deposits/${d.id}/scan`}:{step:2,label:'Go to the Hub',to:`/deposits/${d.id}`};}
function useDepositSteps(d:Deposit|null){ const {t}=useI18n(); const navigate=useNavigate();const [busy,setBusy]=useState(false);const [error,setError]=useState<Message>('');
  async function findArea(){if(!d||busy)return;setBusy(true);setError('');try{const r=await api<{deposit:Deposit}>(`/deposits/${d.id}/arrive`,{});navigate(`/deposits/${d.id}/${r.deposit.verified_zone_id===r.deposit.zone_id?'place':'scan'}`);}catch(e){setError(messageOf(e));}finally{setBusy(false);}}
  const root=d?`/deposits/${d.id}`:'';const verified=!!d&&d.verified_zone_id===d.zone_id;
  const steps:FlowStep[]=[{label:t('Add information'),to:d?`${root}/edit`:undefined},{label:t('Go to the Hub'),to:d?`${root}/guide`:undefined},{label:t('Find area'),to:d?.arrived_at?`${root}/scan`:undefined,onClick:d&&!d.arrived_at?()=>void findArea():undefined,disabled:busy},{label:t('Drop off'),to:verified?`${root}/place`:undefined}];
  return {steps,findArea,busy,error};
}
function Title({title,subtitle}:{title:string;subtitle?:string}){ const {t,msg,language}=useI18n(); return <div className="page-heading"><h1>{title}</h1>{subtitle&&<p>{subtitle}</p>}</div>;}

export function PhotoUpload({photos,onChange,max,label,disabled=false,onBusy,optional=false}:{photos:Photo[];onChange:(p:Photo[])=>void;max:number;label:string;disabled?:boolean;onBusy?:(b:boolean)=>void;optional?:boolean}) { const {t,msg,language}=useI18n(); 
  const [busy,setBusy]=useState(false);const [error,setError]=useState<Message>('');const [progress,setProgress]=useState<Message>('');
  async function select(e:ChangeEvent<HTMLInputElement>) {
    const files=Array.from(e.target.files||[]);e.target.value='';if(!files.length)return;
    setError('');
    if(files.length+photos.length>max){setError({key:'You can upload a maximum of {{max}} photos.',values:{max}});return;}
    for(const f of files){if(!['image/jpeg','image/png','image/webp'].includes(f.type)||! /\.(jpe?g|png|webp)$/i.test(f.name)){setError('Use JPG, JPEG, PNG or WebP only. Videos are not supported.');return;}if(f.size>10*1024*1024){setError('Each photo must be 10MB or smaller.');return;}}
    setBusy(true);onBusy?.(true);const added=[...photos];
    try {for(const [i,file] of files.entries()){
      setProgress(`Uploading photo ${i+1} of ${files.length}…`);
      const response=await fetch('/api/uploads',{method:'POST',credentials:'same-origin',headers:{'Content-Type':file.type,'X-File-Name':encodeURIComponent(file.name)},body:file});
      const result=await response.json();if(!response.ok)throw new ApiError(result);
      added.push(result.photo);onChange([...added]);
    }}catch(e){setError(messageOf(e));}finally{setBusy(false);onBusy?.(false);setProgress('');}
  }
  return <section className="photo-field"><div className="field-heading"><b>{label} <span className="required">{optional?"(optional)":"*"}</span></b><small>{photos.length}/{max}</small></div><p className="field-help">{optional?"Up to":"1–"}{max} photos{max===9?" · First photo is the cover":""}. JPG, PNG or WebP, up to 10MB.</p><div className="photo-grid">{photos.map((p,i)=><div className="photo-preview" key={p.id}><MaterialPhoto src={p.url} alt={`${label} ${i+1}`}/>{max===9&&i===0&&<span className="cover-label">{t("Cover")}</span>}<button type="button" aria-label={t("Remove {{label}} {{index}}",{label:label.toLowerCase(),index:i+1})} disabled={disabled||busy} onClick={()=>onChange(photos.filter(x=>x.id!==p.id))}><Trash2 size={15}/></button>{max===9&&i>0&&<button className="make-cover" type="button" disabled={disabled||busy} onClick={()=>onChange([p,...photos.filter(x=>x.id!==p.id)])} aria-label={t("Make photo {{index}} the cover",{index:i+1})}>{t("Make cover")}</button>}</div>)}</div><div className="upload-actions"><label className={`upload-choice ${disabled||busy||photos.length>=max?'disabled':''}`}><ImagePlus size={18}/>{t("Choose photos")}<input aria-label={t("{{label}} from gallery",{label})} type="file" accept="image/jpeg,image/png,image/webp,.jpg,.jpeg,.png,.webp" multiple disabled={disabled||busy||photos.length>=max} onChange={select}/></label><label className={`upload-choice ${disabled||busy||photos.length>=max?'disabled':''}`}><Camera size={18}/>{t("Take a photo")}<input aria-label={t("{{label}} from camera",{label})} type="file" accept="image/jpeg,image/png,image/webp" capture="environment" disabled={disabled||busy||photos.length>=max} onChange={select}/></label></div>{progress&&<p role="status" className="field-help">{msg(progress)}</p>}<ErrorMessage error={error}/></section>;
}

export function AddInformation() { const {t,msg,language}=useI18n(); 
  const {user}=useAccount();const {id}=useParams();const navigate=useNavigate();const editing=!!id;const fresh=new URLSearchParams(useLocation().search).has('fresh');
  const [additionalOpen,setAdditionalOpen]=useState(false);
  const [form,setForm]=useState<FormData>(blank);const [photos,setPhotos]=useState<Photo[]>([]);const [categories,setCategories]=useState<{id:number;name:string}[]>([]);
  const [ready,setReady]=useState(false);const [deposit,setDeposit]=useState<Deposit|null>(null);const {steps}=useDepositSteps(deposit);const [version,setVersion]=useState(0);const [error,setError]=useState<Message>('');const [saving,setSaving]=useState(false);const [uploading,setUploading]=useState(false);const [draftState,setDraftState]=useState<Message>('');
  const saveQueue=useRef<Promise<unknown>>(Promise.resolve());const revision=useRef(0);
  useEffect(()=>{if(!user)return;let active=true;setReady(false);setError('');
    Promise.all([api<{categories:{id:number;name:string}[]}>('/categories'),editing?api<{deposit:Deposit}>(`/deposits/${id}`):api<{draft:FormData|null}>('/deposit-draft')]).then(([c,r])=>{
      if(!active)return;setCategories(c.categories);
      if('deposit' in r){const d=r.deposit;if(d.deposit_status==='confirmed'){navigate(`/deposits/${id}/success`,{replace:true});return;}setDeposit(d);setVersion(d.version);setForm({request_key:'editing',name:d.name,category_id:String(d.category_id),custom_category_name:d.custom_category_name||'',quantity:String(d.initial_quantity),unit:d.unit,dimensions_spec:d.dimensions_spec||'',dimensions_not_applicable:!!d.dimensions_not_applicable,color:d.color,condition:d.condition,reference_url:d.reference_url||'',notes:d.notes,photo_ids:d.photos.map(p=>p.id)});setPhotos(d.photos);setAdditionalOpen(!!(d.notes||d.reference_url));}
      else if(r.draft&&!fresh){setForm(r.draft);setPhotos(r.draft.photo_ids.map(photoId=>({id:photoId,url:`/api/media/${photoId}`})));setDraftState('Draft restored from your account.');setAdditionalOpen(!!(r.draft.notes||r.draft.reference_url));}
      else {setForm(blank());setPhotos([]);setAdditionalOpen(false);}
      setReady(true);if(fresh&&!editing)navigate('/deposit/new',{replace:true});
    }).catch(e=>{if(active)setError(messageOf(e));});return()=>{active=false;};
  },[user?.id,id]);
  function change(next:FormData) {
    setForm(next);if(editing)return;
    const rev=++revision.current;setDraftState('Saving draft…');
    saveQueue.current=saveQueue.current.catch(()=>{}).then(()=>api('/deposit-draft',next)).then(()=>{if(rev===revision.current)setDraftState('Draft saved to your account.');}).catch(e=>{if(rev===revision.current)setDraftState({key:'Draft not saved: {{error}}',values:{error:messageOf(e)}});});
  }
  function field(key:keyof FormData,value:string|boolean){change({...form,[key]:value});}
  function photoChange(next:Photo[]){setPhotos(next);change({...form,photo_ids:next.map(p=>p.id)});}
  async function submit(e:FormEvent){e.preventDefault();const invalid=(e.currentTarget as HTMLFormElement).querySelector(':invalid');const group=invalid?.closest('details');if(group)group.open=true;const validation=validateForm(e.currentTarget as HTMLFormElement);if(validation){setError(validation);return;}if(saving||uploading)return;setError('');if(!photos.length){setError('Please upload at least 1 material photo.');return;}setSaving(true);try{await saveQueue.current;const r=await api<{deposit:Deposit}>(editing?`/deposits/${id}/edit`:'/deposits',{...form,photo_ids:photos.map(p=>p.id),...(editing?{version}:{})});navigate(`/deposits/${r.deposit.id}?review=1`);}catch(e){setError(messageOf(e));}finally{setSaving(false);}}
  if(!user)return <div className="loading">{t("Loading your account…")}</div>;
  if(!ready)return <div className="flow-page"><ErrorMessage error={error}/>{!error&&<div className="loading">{t("Loading your material…")}</div>}<Link to="/deposit">{t("Back to Share Material")}</Link></div>;
  return <div className="flow-page"><Link className="back-link" to={editing?`/deposits/${id}?review=1`:'/deposit'}><ArrowLeft size={16}/>{t("Back")}</Link><StepBar steps={steps} current={1}/><Title title={t("Add Information")} subtitle="Fields marked * are required."/><form className="material-form" noValidate onSubmit={submit}><fieldset disabled={saving||uploading}><PhotoUpload label={t("Material photos")} photos={photos} max={9} onChange={photoChange} onBusy={setUploading}/>
    <label>{t("Material name")}{" "}<span>*</span><input required maxLength={200} value={form.name} onChange={e=>field('name',e.target.value)} placeholder={t("e.g. Foam board offcuts")}/></label>
    <label>{t("Category")}{" "}<span>*</span><select required value={form.category_id} onChange={e=>field('category_id',e.target.value)}><option value="">{t("Choose a category")}</option>{categories.map(c=><option key={c.id} value={c.id}>{t(c.name)}</option>)}</select></label>
    {form.category_id==='7'&&<label>{t("Custom category name")}{" "}<span>*</span><input required maxLength={200} value={form.custom_category_name} onChange={e=>field('custom_category_name',e.target.value)}/></label>}
    <div className="form-row"><label>{t("Quantity")}{" "}<span>*</span><input type="number" inputMode="numeric" required min="1" max="1000000" step="1" value={form.quantity} onChange={e=>field('quantity',e.target.value)}/></label><label>{t("Unit")}{" "}<span>*</span><input required maxLength={50} list="units" value={form.unit} onChange={e=>field('unit',e.target.value)} placeholder={t("e.g. sheets")}/><datalist id="units">{['sheets','pieces','panels','rolls','sets'].map(v=><option key={v} value={v} label={t(v)}/>)}</datalist></label></div>
    <label>{t("Dimensions / specifications")}{" "}<span>*</span><input required={!form.dimensions_not_applicable} disabled={form.dimensions_not_applicable} maxLength={500} value={form.dimensions_spec} onChange={e=>field('dimensions_spec',e.target.value)} placeholder={t("e.g. A3, 5 mm thick")}/></label><label className="checkbox-label"><input type="checkbox" checked={form.dimensions_not_applicable} onChange={e=>field('dimensions_not_applicable',e.target.checked)}/>{t("Not applicable")}</label>
    <label>{t("Color")}{" "}<span>*</span><input required maxLength={80} value={form.color} onChange={e=>field('color',e.target.value)} placeholder={t("e.g. White")}/></label>
    <label>{t("Condition")}{" "}<span>*</span><select required value={form.condition} onChange={e=>field('condition',e.target.value)}><option value="">{t("Choose")}</option>{['New','Like new','Good','Used'].map(v=><option key={v} value={v}>{t(v)}</option>)}</select></label>
    <details className="optional-details" open={additionalOpen} onToggle={e=>setAdditionalOpen(e.currentTarget.open)}><summary>Additional details (optional)<ChevronRight size={18}/></summary><label>{t("Purchase / reference link")}{" "}<small>{t("Optional")}</small><input type="url" maxLength={2000} value={form.reference_url} onChange={e=>field('reference_url',e.target.value)} placeholder="https://"/></label><label>{t("Notes")}{" "}<small>{t("Optional")}</small><textarea maxLength={4000} value={form.notes} onChange={e=>field('notes',e.target.value)} placeholder={t("Anything the next maker should know?")} rows={4}/></label></details>
    <ErrorMessage error={error}/><p className="field-help" role="status">{editing?t("Changes to the category require a new Zone scan."):msg(draftState)}</p><button className="button dark full flow-primary" disabled={saving||uploading} type="submit">{saving?t("Saving…"):editing?t("Save changes"):t("Next")}</button><p className="subtle-note">{t("Saving records your material. Your 1 credit is earned after you complete the drop-off.")}</p></fieldset></form></div>;
}

function DepositStrip({d}:{d:Deposit}) { return <MaterialStrip image={d.photos[0]?.url} name={d.name} code={d.display_code} editTo={`/deposits/${d.id}/edit`}><DepositDetails d={d}/></MaterialStrip>; }
function DepositDetails({d}:{d:Deposit}) { const {t}=useI18n(); return <>{d.photos.length>0&&<div className="record-thumbnails">{d.photos.map((p,i)=><MaterialPhoto key={p.id} src={p.url} alt={t("Material photo {{index}}",{index:i+1})}/>)}</div>}<dl className="specs"><div><dt>{t("Category")}</dt><dd>{t(d.category)}{d.custom_category_name?` · ${d.custom_category_name}`:''}</dd></div><div><dt>{t("Quantity")}</dt><dd>{d.initial_quantity} {d.unit}</dd></div><div><dt>{t("Dimensions")}</dt><dd>{d.dimensions_not_applicable?t("Not applicable"):d.dimensions_spec}</dd></div><div><dt>{t("Color / Condition")}</dt><dd>{d.color} / {d.condition}</dd></div><div><dt>{t("Zone")}</dt><dd>{t(d.zone)}</dd></div></dl>{d.reference_url&&<a className="text-link wrap-link" href={d.reference_url} target="_blank" rel="noreferrer">{t("Purchase / reference link ↗")}</a>}{d.notes&&<p className="notes-text">{d.notes}</p>}</>;}

export function CameraScanner({onScan,autoStart=false}:{onScan:(qr:string)=>Promise<void>;autoStart?:boolean}) { const {t,msg,language}=useI18n(); 
  const video=useRef<HTMLVideoElement>(null);const controls=useRef<IScannerControls|null>(null);const stream=useRef<MediaStream|null>(null);const generation=useRef(0);const mounted=useRef(true);const [state,setState]=useState<'idle'|'starting'|'running'>('idle');const [error,setError]=useState<Message>('');const last=useRef({qr:'',at:0});const verifying=useRef(false);
  function stop(){generation.current++;controls.current?.stop();controls.current=null;stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;if(video.current)video.current.srcObject=null;}
  useEffect(()=>{mounted.current=true;if(autoStart)void start();return()=>{mounted.current=false;stop();};},[]);
  async function start(){stop();const session=generation.current;setError('');setState('starting');
    try{
      if(!window.isSecureContext||!navigator.mediaDevices?.getUserMedia)throw new Error('Camera access needs localhost or HTTPS. Open this page in a camera-enabled browser.');
      const media=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1280}},audio:false});
      if(!mounted.current||generation.current!==session){media.getTracks().forEach(t=>t.stop());return;}stream.current=media;
      const {BrowserQRCodeReader}=await import('@zxing/browser');
      if(!mounted.current||generation.current!==session){media.getTracks().forEach(t=>t.stop());return;}
      const reader=new BrowserQRCodeReader(undefined,{delayBetweenScanAttempts:250});
      const scan=await reader.decodeFromStream(media,video.current!,async(result)=>{
        if(!result||verifying.current||!mounted.current||generation.current!==session)return;const qr=result.getText();if(qr===last.current.qr&&Date.now()-last.current.at<2500)return;last.current={qr,at:Date.now()};verifying.current=true;
        try{await onScan(qr);stop();}catch(e){if(mounted.current)setError(messageOf(e));}finally{verifying.current=false;}
      });
      if(!mounted.current||generation.current!==session){scan.stop();media.getTracks().forEach(t=>t.stop());return;}controls.current=scan;setState('running');
    }catch(e){stop();if(!mounted.current)return;setState('idle');const err=e as Error;setError(err.name==='NotAllowedError'?'Camera permission was denied. Enable camera access in your browser settings, then try again.':err.name==='NotFoundError'?'No camera was found. Connect a camera and try again.':err.name==='NotReadableError'?'The camera is in use. Close other camera apps and try again.':messageOf(err));}
  }
  return <section className="scanner"><div className="camera-window"><video ref={video} muted playsInline autoPlay aria-label={t("Zone QR camera preview")}/>{state==='idle'&&<div className="camera-prompt"><Camera size={38}/><p>{t("Point your camera at the Zone QR.")}</p></div>}<span className="scan-corners"/></div><ErrorMessage error={error}/>{state==='running'?<><p className="field-help" role="status">{t("Camera active. Keep the QR inside the frame.")}</p><button className="button outline full" onClick={()=>{stop();setState('idle');}}>{t("Stop camera")}</button></>:<button className="button dark full" disabled={state==='starting'} onClick={start}>{state==='starting'?t("Opening camera…"):error?t("Retry camera"):t("Start camera")}<Camera size={18}/></button>}<p className="subtle-note">{t("Camera scanning only. Enable camera permission if asked.")}</p></section>;
}

export function DepositPage(){ const {t,msg,language}=useI18n(); 
  const {user,setUser}=useAccount();const {id,stage}=useParams();const location=useLocation();const navigate=useNavigate();
  const [loadedFor,setLoadedFor]=useState('');const routeKey=`${id}/${stage||''}`;
  const [d,setD]=useState<Deposit|null>(null);const [error,setError]=useState<Message>('');const [busy,setBusy]=useState(false);const [uploading,setUploading]=useState(false);const [placement,setPlacement]=useState<Photo[]>([]);const [photoSaving,setPhotoSaving]=useState(false);const [photoError,setPhotoError]=useState<Message>('');const queue=useRef<Promise<unknown>>(Promise.resolve());const photoRevision=useRef(0);
  const {steps,findArea,busy:entering,error:stepError}=useDepositSteps(d);
  useEffect(()=>{if(!user)return;let active=true;setError('');setD(null);api<{deposit:Deposit}>(`/deposits/${id}`).then(r=>{if(active){setD(r.deposit);setPlacement(r.deposit.placement_photos);setPhotoError('');setLoadedFor(routeKey);}}).catch(e=>{if(active)setError(messageOf(e));});return()=>{active=false;};},[user?.id,id,stage]);
  if(!user)return <div className="loading">{t("Loading your account…")}</div>;
  if(!d||loadedFor!==routeKey)return <div className="flow-page"><ErrorMessage error={error}/>{!error&&<div className="loading">{t("Loading your material…")}</div>}<Link to="/me/posts">{t("My Posts")}</Link></div>;
  if(d.deposit_status==='confirmed'&&stage!=='success')return <Navigate to={`/deposits/${id}/success`} replace/>;
  if(stage==='success'&&d.deposit_status!=='confirmed')return <Navigate to={`/deposits/${id}`} replace/>;
  if(!stage&&d.verified_zone_id===d.zone_id&&!new URLSearchParams(location.search).has('review'))return <Navigate to={`/deposits/${id}/place`} replace/>;
  if(stage==='place'&&d.verified_zone_id!==d.zone_id)return <Navigate to={`/deposits/${id}/${d.arrived_at?'scan':'guide'}`} replace/>;
  if(stage==='scan'&&!d.arrived_at)return <Navigate to={`/deposits/${id}/guide`} replace/>;
  if(stage==='scan'&&d.verified_zone_id===d.zone_id)return <Navigate to={`/deposits/${id}/place`} replace/>;
  function savePlacement(photos:Photo[]){setPlacement(photos);setPhotoSaving(true);setPhotoError('');const revision=++photoRevision.current;queue.current=queue.current.catch(()=>{}).then(()=>api(`/deposits/${id}/placement`,{photo_ids:photos.map(p=>p.id)})).catch(e=>{if(revision===photoRevision.current)setPhotoError(messageOf(e));throw e;}).finally(()=>{if(revision===photoRevision.current)setPhotoSaving(false);});queue.current.catch(()=>{});}
  async function confirm(){setBusy(true);setError('');try{await queue.current;await api(`/deposits/${id}/confirm`,{});const auth=await api<{user:User}>('/auth/me');setUser(auth.user);navigate(`/deposits/${id}/success`);}catch(e){setError(messageOf(e));}finally{setBusy(false);}}
  const root=`/deposits/${id}`;
  if(stage==='steps')return <Navigate to="/deposit" replace/>;
  const hubButton=<button className="button dark full flow-primary" onClick={()=>void findArea()} disabled={entering}>{entering?t("Opening…"):t("I’m at the Hub")}</button>;
  return <div className="flow-page">{stage!=='success'&&<><Link className="back-link" to="/deposit"><ArrowLeft size={16}/>{t("Share")}</Link><StepBar steps={steps} current={stage==='place'?4:stage==='scan'?3:2}/><DepositStrip d={d}/></>}
    {!stage&&<><Title title={t("Material Recorded")} subtitle={t("Now you can go to the Hub.")}/><p className="field-help">{t("It’s registered but not on the shelf yet. Need directions? Tap “Go to the Hub” above.")}</p>{hubButton}</>}
    {stage==='guide'&&<><Title title={t("Go to the Hub")} subtitle={t("Your drop-off guide, one step at a time.")}/><HubGuideContent zone={d.zone} zoneId={d.zone_id}/>{hubButton}</>}
    {stage==='scan'&&<><Title title={t("Find Area")} subtitle={t("Scan the Zone QR to confirm you are in the right place.")}/><div className="zone-confirm"><MapPin size={21}/><div><small>{t("YOUR MATERIAL ZONE")}</small><b>{t(d.zone)}</b></div></div><CameraScanner autoStart onScan={async qr=>{await api(`/deposits/${id}/verify-zone`,{qr});navigate(`${root}/place`);}}/></>}
    {stage==='place'&&<><Title title={t("Drop Off Material")} subtitle={t("You’re in the right zone. Give your material a home.")}/><div className="zone-confirm"><CheckCircle2 size={24}/><div><small>{t("ZONE CONFIRMED")}</small><b>{t(d.zone)}</b></div></div><ol className="placement-guide"><li><b>{t("Write and attach your label")}</b><p>{t("Take a blank label from Material Hub. Write the code below and attach it to the material or its packaging.")}</p><strong className="label-code">{d.display_code}</strong><p>{d.name} · {d.initial_quantity} {d.unit}</p></li><li><b>{t("Place it on the shelf")}</b><p>{t("Leave it in the {{zone}} Zone, with the label clearly visible.",{zone:t(d.zone)})}</p></li><li><b>{t("Take a placement photo")}</b><p>{t("Show the material and its surroundings so the next maker can find it.")}</p></li></ol><PhotoUpload photos={placement} onChange={savePlacement} max={3} label={t("Placement photos")} disabled={busy} onBusy={setUploading}/>{photoSaving&&<p role="status" className="field-help">{t("Saving placement photos…")}</p>}<ErrorMessage error={photoError}/>{photoError&&<button className="button outline full" onClick={()=>savePlacement(placement)}>{t("Retry saving photos")}</button>}<button className="button dark full flow-primary" disabled={busy||uploading||photoSaving||!!photoError||!placement.length} onClick={confirm}>{busy?t("Confirming…"):t("Confirm drop-off")}<Check size={18}/></button><p className="subtle-note">{t("You earn 1 credit only after confirming. Photos and progress are saved to your account.")}</p></>}
    {stage==='success'&&<CompletionSummary title="Material Confirmed" description={d.status==='available'?'Your material is ready to be picked up.':d.status==='unavailable'?'This material is paused while a reported problem awaits review.':d.status==='reserved'?'This material is reserved for pickup.':d.status==='collected'?'All available material has been collected.':'This material is no longer available.'} name={d.name} code={d.display_code} quantity={d.stock_quantity+' '+d.unit+' remaining · '+d.collected_quantity+' collected'} image={d.photos[0]?.url} credit="+1 credit earned">{d.issues?.length>0&&<section className="issue-summary"><b>{d.status==='closed'?'Removed / Archived':'Needs Review'}</b>{d.issues.map(i=><div key={i.id}><b>Reported: {i.reason_label||i.reason.replaceAll('_',' ')} · {i.status}</b><p className="notes-text">{i.notes}</p><div className="record-thumbnails">{i.photos.map(p=><MaterialPhoto key={p.id} src={p.url} alt="Reported problem"/>)}</div></div>)}</section>}</CompletionSummary>}
    <ErrorMessage error={error||stepError}/>
  </div>;
}

export function ShareMaterial(){ const {t}=useI18n();
  const{user,loading}=useContext(Auth);const[draftName,setDraftName]=useState<string>();const[rows,setRows]=useState<Deposit[]|null>(null);const[error,setError]=useState<Message>('');
  useEffect(()=>{let active=true;setDraftName(undefined);setRows(null);setError('');if(user){api<{draft:FormData|null}>('/deposit-draft').then(r=>{if(active)setDraftName(r.draft?.name);}).catch(()=>{});api<{deposits:Deposit[]}>('/deposits').then(r=>{if(active)setRows(r.deposits.filter(d=>d.deposit_status==='pending'));}).catch(e=>{if(active)setError(messageOf(e));});}return()=>{active=false;};},[user?.id]);
  return <div className="flow-page share-page"><Title title={t("Share Material")} subtitle={t("Earn 1 credit after completing your drop-off.")}/><Link className="button dark full" to="/deposit/new?fresh=1"><Plus size={18}/>{t("Add new material")}</Link>{draftName!==undefined&&<Link className="draft-resume" to="/deposit/new"><span>{t("Continue draft")}{draftName?': '+draftName:''}</span><ChevronRight size={18}/></Link>}
    <section className="share-active"><div className="section-title"><h2>{t("In progress")}</h2></div><p className="field-help">{t("Choose a material to continue its drop-off at the Hub.")}</p><ErrorMessage error={error}/>
    {loading?null:!user?<div className="task-empty"><div><b>{t("Log in to share materials")}</b><p>{t("Your materials in progress will appear here.")}</p></div><Link to="/login?next=/deposit" aria-label={t("Log in")}><ArrowRight size={22}/></Link></div>:!rows?!error&&<p className="loading">{t("Loading…")}</p>:rows.length?<div className="post-list">{rows.map(d=>{const at=depositStage(d);return <Link className="active-task" key={d.id} to={at.to}><MaterialPhoto src={d.photos[0]?.url} alt={d.name}/><div><span>{d.display_code}</span><b>{d.name}</b><small>{t("Step {{step}} of 4 · {{label}}",{step:at.step,label:t(at.label)})}</small></div><ChevronRight size={18}/></Link>;})}</div>:<div className="task-empty"><span className="soft-icon"><Package size={22}/></span><div><b>{t("Nothing in progress")}</b><p>{t("Add a material to get started. It stays here until you drop it off.")}</p></div></div>}</section></div>;
}

function HubGuideContent({zone,zoneId}:{zone?:string;zoneId?:number}){
  return <><div className="guide-block"><h2>Find Material Hub</h2><div className="guide-placeholder"><MapPin size={35}/><b>Material Hub</b><span>Building 17 · L1</span><span>Opening hours to be confirmed</span><small>Route map coming soon</small></div></div><div className="guide-block"><h2>{zone?'Find '+zone:'Find your material zone'}</h2>{zone?<div className="guide-placeholder"><Package size={35}/><b>{zone} Zone</b><small>Zone photo coming soon</small></div>:<p>Your material category determines its zone. The drop-off screen shows the zone for the material you select.</p>}</div><div className="guide-block"><h2>Look for the Zone QR</h2>{zoneId&&<MaterialPhoto className="guide-qr" src={`/api/zones/${zoneId}/qr`} alt={`${zone} Zone QR example`}/>}<p>Scan the sign at the zone to confirm your location. This QR identifies the zone, not an individual material.</p></div></>;
}
export function HubGuide(){return <div className="flow-page"><Link className="back-link" to="/deposit"><ArrowLeft size={18}/>Share Material</Link><Title title="Go to the Hub" subtitle="Your drop-off guide, one step at a time."/><HubGuideContent/><Link className="button dark full" to="/deposit/drop-off">I'm at the Hub</Link></div>;}

export function DropOffEntry(){
  const{user,loading}=useContext(Auth);const navigate=useNavigate();
  const[rows,setRows]=useState<Deposit[]>([]),[ready,setReady]=useState(false),[error,setError]=useState<Message>(''),[busy,setBusy]=useState<number|null>(null),[revision,setRevision]=useState(0);
  const entering=useRef(false);
  async function enter(d:Deposit){if(entering.current)return;entering.current=true;setBusy(d.id);setError('');try{const result=await api<{deposit:Deposit}>(`/deposits/${d.id}/arrive`,{});navigate(`/deposits/${d.id}/${result.deposit.verified_zone_id===result.deposit.zone_id?'place':'scan'}`,{replace:true});}catch(e){setError(messageOf(e));}finally{entering.current=false;setBusy(null);}}
  useEffect(()=>{let active=true;setReady(false);setError('');if(!user){setRows([]);setReady(true);return;}api<{deposits:Deposit[]}>('/deposits').then(r=>{if(!active)return;const pending=r.deposits.filter(d=>d.deposit_status==='pending');setRows(pending);setReady(true);if(pending.length===1)void enter(pending[0]);}).catch(e=>{if(active){setError(messageOf(e));setReady(true);}});return()=>{active=false;};},[user?.id,revision]);
  return <div className="flow-page"><Link className="back-link" to="/deposit"><ArrowLeft size={18}/>Share Material</Link><Title title="Scan Zone QR" subtitle={rows.length>1?'Choose the material you are dropping off.':'Continue your drop-off at the Hub.'}/><ErrorMessage error={error}/>{loading||!ready||busy!==null?<p className="loading">Opening your drop-off…</p>:!user?<><p>Log in to find your pending materials.</p><Link className="button dark full spaced" to="/login?next=/deposit/drop-off">Log in</Link></>:rows.length?<div className="post-list">{rows.map(d=><button className="active-task pending-choice" key={d.id} onClick={()=>void enter(d)}><MaterialPhoto src={d.photos[0]?.url} alt=""/><div><b>{d.name}</b><small>{d.display_code} · {d.zone}</small></div><ChevronRight size={18}/></button>)}</div>:!error?<div className="empty-state"><Package size={30}/><h2>No materials ready for drop-off</h2><p>Add your material information first. You will then receive a material code and can scan its Zone QR.</p><Link className="button dark full" to="/deposit/new?fresh=1">Add material</Link></div>:<button className="button outline" onClick={()=>setRevision(n=>n+1)}>Retry</button>}</div>;
}
export function DepositTasks({compact=false}:{compact?:boolean}){
  const{user}=useContext(Auth);const[deposits,setDeposits]=useState<Deposit[]>([]);const[reservations,setReservations]=useState<Reservation[]>([]);const[error,setError]=useState<Message>('');
  useEffect(()=>{if(!user){setDeposits([]);setReservations([]);return;}let active=true;const load=()=>Promise.all([api<{deposits:Deposit[]}>('/deposits'),api<{reservations:Reservation[]}>('/me/reservations')]).then(([d,r])=>{if(active){setDeposits(d.deposits.filter(x=>x.deposit_status==='pending'));setReservations(r.reservations.filter(x=>x.status==='reserved'));}}).catch(e=>{if(active)setError(messageOf(e));});void load();const timer=setInterval(load,15000);return()=>{active=false;clearInterval(timer);};},[user?.id]);
  if(!deposits.length&&!reservations.length&&!error)return null;
  if(compact)return <Link className="compact-task" to={reservations.length?'/me/reservations':'/deposit'}><Clock3 size={18}/><span>{deposits.length+reservations.length} active task{deposits.length+reservations.length===1?'':'s'} · Continue</span><ChevronRight size={18}/></Link>;
  return <section className="tasks"><div className="section-title"><h2>Your Active Tasks</h2></div><ErrorMessage error={error}/>{deposits.length||reservations.length?<div className="task-strip">{reservations.map(r=><Link className="active-task" key={'r'+r.id} to={'/reservations/'+r.id}><MaterialPhoto src={r.image} alt={r.name}/><div><span>{r.display_code}</span><b>{r.name}</b><small>Reserved for pickup<br/><Remaining expires={r.expires_at}/></small></div><ChevronRight size={18}/></Link>)}{deposits.map(d=><Link className="active-task" key={d.id} to={depositStage(d).to}><MaterialPhoto src={d.photos[0]?.url} alt={d.name}/><div><span>{d.display_code}</span><b>{d.name}</b><small>Step {depositStage(d).step} of 4 · {depositStage(d).label}</small></div><ChevronRight size={18}/></Link>)}</div>:<div className="task-empty"><span className="soft-icon"><Check size={22}/></span><div><b>{user?'A fresh start. Nothing pending.':'Your next chapter starts here.'}</b><p>{user?'Your drop-offs and reservations will appear here.':'Log in to reserve, or create an account with 2 credits.'}</p></div><Link to={user?'/deposit':'/register'} aria-label={user?'Share material':'Create account'}><ArrowRight size={22}/></Link></div>}</section>;
}
export function MyPosts(){return <ManagedPosts/>;}
