import { ArrowLeft } from 'lucide-react';
import { useContext, useEffect, useRef, useState } from 'react';
import { Link, Navigate, useNavigate, useParams } from 'react-router-dom';
import { Auth, api, type User } from './lib';
import { CameraScanner, PhotoUpload } from './deposits';
import type { Reservation } from './reservations';
import { MaterialStrip, StepBar } from './ui';

type Photo={id:number;url:string};
export type FulfillmentFields={verified_zone_id:number|null;zone_id_snapshot:number;material_code_verified_at:string|null;completed_at:string|null;return_deadline_at:string|null;can_return:boolean;dimensions_spec:string;dimensions_not_applicable:number;condition:string;placement_photos:Photo[];issue:{reason_label:string;reason:string;notes:string;status:string;resolution:string|null;photos:Photo[]}|null;return:{verified_zone_id:number|null;status:string;photos:Photo[]}|null};
const reasons=['Material is missing','Wrong material','Damaged','Does not match the listing','Other'];
export function ReservationOutcome({r}:{r:Reservation}) {
  return <>{r.status==='reserved'&&<Link className="button dark full spaced" to={`/reservations/${r.id}/guide`}>View pickup guide</Link>}
    {r.completed_at&&<p className="field-help">Collected: {new Date(r.completed_at).toLocaleString('en')}</p>}
    {r.status==='collected'&&<><p className="field-help">1 credit spent. Return deadline: {new Date(r.return_deadline_at!).toLocaleString('en',{dateStyle:'medium',timeStyle:'long'})}</p>{r.can_return&&Date.parse(r.return_deadline_at!)>Date.now()?<Link className="button outline full" to={`/reservations/${r.id}/return`}>Return Material</Link>:<p className="field-help">The 24-hour return window has ended.</p>}</>}
    {r.status==='returned'&&<p className="field-help">All reserved material returned. 1 credit refunded.</p>}
    {r.issue&&<section className="issue-summary"><b>{r.issue.status==='open'?'Issue Reported · Open — Needs Review':'Issue resolved — '+r.issue.resolution}</b><p>{r.issue.reason_label||r.issue.reason.replaceAll('_',' ')}</p><p className="notes-text">{r.issue.notes}</p><p className="field-help">1 credit released. {r.issue.status==='open'?'This material is hidden from Explore pending review.':r.issue.resolution==='relisted'?'The provider reviewed and relisted the material.':'The provider removed this material from Explore.'}</p><div className="record-thumbnails">{r.issue.photos.map(p=><img key={p.id} src={p.url} alt="Reported problem"/>)}</div></section>}
  </>;
}
function Summary({r}:{r:Reservation}) {return <><h2>{r.name}</h2><strong className="material-code">{r.display_code}</strong><dl className="specs"><div><dt>Reservation quantity</dt><dd>{r.reserved_quantity} {r.unit_snapshot}</dd></div><div><dt>Dimensions</dt><dd>{r.dimensions_not_applicable?'Not applicable':r.dimensions_spec}</dd></div><div><dt>Condition</dt><dd>{r.condition}</dd></div><div><dt>Zone</dt><dd>{r.zone}</dd></div></dl><h2>Placement photo</h2>{r.placement_photos.length?<div className="material-gallery spaced">{r.placement_photos.map(p=><img key={p.id} src={p.url} alt="Material placement"/>)}</div>:<p className="field-help">No placement photo is available for this demo material.</p>}</>;}
export function FulfillmentPage(){
  const{id,stage}=useParams();const{user,loading,setUser}=useContext(Auth);const navigate=useNavigate();
  const[r,setR]=useState<Reservation|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[revision,setRevision]=useState(0);
  const[code,setCode]=useState(''),[verified,setVerified]=useState(false),[reason,setReason]=useState(''),[notes,setNotes]=useState(''),[photos,setPhotos]=useState<Photo[]>([]),[uploading,setUploading]=useState(false),[placed,setPlaced]=useState(false),[photoError,setPhotoError]=useState(''),[savingPhotos,setSavingPhotos]=useState(false);
  const lock=useRef(false),queue=useRef<Promise<unknown>>(Promise.resolve()),photoRevision=useRef(0);
  const routeKey=[user?.id,id,stage].join('/');const[loadedFor,setLoadedFor]=useState('');
  const returning=stage?.startsWith('return');const root=`/reservations/${id}`;
  useEffect(()=>{if(!user)return;let live=true;setR(null);setError('');setVerified(false);setCode('');setPlaced(false);setPhotos([]);setPhotoError('');
    const load=async()=>{const result=await api<{reservation:Reservation}>(root+(stage==='return'?'/return/start':''),stage==='return'?{}:undefined);if(live){setR(result.reservation);setLoadedFor(routeKey);if(returning)setPhotos(result.reservation.return?.photos||[]);}};
    void load().catch(e=>{if(live)setError(e.message);});return()=>{live=false;};
  },[id,stage,user?.id,revision]);
  async function action(path:string,body:unknown,next?:string){if(lock.current)return;lock.current=true;setBusy(true);setError('');try{await queue.current;const result=await api<{reservation:Reservation}>(`${root}/${path}`,body);if(!next)setR(result.reservation);if(path==='verify-material')setVerified(true);if(next)navigate(next);void api<{user:User}>('/auth/me').then(a=>setUser(a.user)).catch(()=>{});}catch(e){setError((e as Error).message);}finally{lock.current=false;setBusy(false);}}
  function savePhotos(next:Photo[]){setPhotos(next);setSavingPhotos(true);setPhotoError('');const v=++photoRevision.current;queue.current=queue.current.catch(()=>{}).then(()=>api(`${root}/return/photos`,{photo_ids:next.map(p=>p.id)})).catch(e=>{if(v===photoRevision.current)setPhotoError(e.message);throw e;}).finally(()=>{if(v===photoRevision.current)setSavingPhotos(false);});void queue.current.catch(()=>{});}
  if(!loading&&!user)return <Navigate to={`/login?next=${encodeURIComponent(location.pathname)}`} replace/>;
  if(!r||loadedFor!==routeKey)return <div className="flow-page"><p>{error||'Loading reservation…'}</p>{error&&<button className="button outline" onClick={()=>setRevision(n=>n+1)}>Retry</button>}<Link className="back-link" to="/me/reservations">My Reservations</Link></div>;
  if(stage==='success'&&!['collected','returned'].includes(r.status))return <Navigate to={root} replace/>;
  if(stage!=='success'&&((returning&&r.status!=='collected')||(!returning&&r.status!=='reserved')))return <Navigate to={root} replace/>;
  if(['check','problem'].includes(stage!)&&r.verified_zone_id!==r.zone_id_snapshot)return <Navigate to={`${root}/scan`} replace/>;
  if(returning&&stage!=='return'&&!r.return)return <Navigate to={root+'/return'} replace/>;
  if(stage==='return-place'&&r.return?.verified_zone_id!==r.zone_id_snapshot)return <Navigate to={`${root}/return`} replace/>;
  const pickupStep=({guide:1,scan:2,check:3,problem:3} as Record<string,number>)[stage||''];
  const zoneVerified=r.verified_zone_id===r.zone_id_snapshot;
  return <div className="flow-page"><Link className="back-link" to={root}><ArrowLeft size={18}/>Reservation details</Link>
    {pickupStep&&<><StepBar current={pickupStep} steps={[{label:'Go to the Hub',to:`${root}/guide`},{label:'Find area',to:`${root}/scan`},{label:'Pick up',to:zoneVerified?`${root}/check`:undefined}]}/><MaterialStrip image={r.image} name={r.name} code={`${r.display_code} · ${r.reserved_quantity} ${r.unit_snapshot}`}/></>}
    {['guide','return'].includes(stage!)&&<><div className="page-heading"><h1>{returning?'Return Guide':'Pickup Guide'}</h1></div><div className="guide-block"><h2>Material Hub</h2><p>Building 17 · L1</p><p>Opening hours to be confirmed</p><div className="guide-placeholder spaced"><b>Route map</b><small>Coming soon</small></div><div className="guide-placeholder spaced"><b>{r.zone} Zone</b><small>Hub and zone photos coming soon</small></div></div><Summary r={r}/>{returning&&<p className="reservation-policy">Return all {r.reserved_quantity} {r.unit_snapshot} to the original Zone. Keep the label attached and upload 1–3 new placement photos. 1 credit will be refunded after confirmation. Deadline: {new Date(r.return_deadline_at!).toLocaleString('en',{dateStyle:'medium',timeStyle:'long'})}.</p>}<button className="button dark full flow-primary" disabled={returning&&!r.can_return} onClick={()=>navigate(`${root}/${returning?'return-scan':'scan'}`)}>I’m at the Hub</button></>}
    {['scan','return-scan'].includes(stage!)&&<><div className="page-heading"><h1>{returning?'Scan Zone QR':'Find Area'}</h1><p>{returning?'Scan the original Zone again to return your material.':'Scan the sign at your reserved material’s Zone.'}</p></div><div className="zone-confirm"><b>{r.zone}</b></div><CameraScanner key={`${id}-${stage}`} autoStart onScan={async qr=>{await api(`${root}/${returning?'return/verify-zone':'verify-zone'}`,{qr});navigate(`${root}/${returning?'return-place':'check'}`);}}/></>}
    {stage==='check'&&<><div className="page-heading"><h1>Check Material</h1></div><Summary r={r}/><form className="material-form" onSubmit={e=>{e.preventDefault();void action('verify-material',{material_code:code});}}><label>Material label code<input value={code} onChange={e=>{setCode(e.target.value);setVerified(false);}} placeholder="M001" autoComplete="off" maxLength={30}/></label><p className="field-help">Enter the code shown on the material label.</p><button className="button outline full" disabled={busy||!code.trim()}>Confirm material code</button></form>{verified&&<section className="action-stack"><h2>Does this material match the listing?</h2><button className="button dark full flow-primary" disabled={busy} onClick={()=>void action('pickup',{material_code:code,matches:true},`${root}/success`)}>Yes, take this material</button><Link className="button outline full" to={`${root}/problem`}>No, report a problem</Link></section>}{!verified&&<Link className="text-link spaced" to={`${root}/problem`}>Material missing or wrong? Report a problem</Link>}</>}
    {stage==='problem'&&<><div className="page-heading"><h1>Report a Problem</h1><p>{r.display_code} · {r.name}</p></div><form className="material-form" onSubmit={e=>{e.preventDefault();void action('issues',{reason,notes,photo_ids:photos.map(p=>p.id)},'/me/reservations');}}><label htmlFor="problem-reason">Reason</label><select id="problem-reason" value={reason} onChange={e=>setReason(e.target.value)}><option value="">Choose a reason</option>{reasons.map(s=><option key={s}>{s}</option>)}</select><label>Description {reason==='Other'?'(required)':'(optional)'}<textarea maxLength={4000} rows={4} value={notes} onChange={e=>setNotes(e.target.value)}/></label><PhotoUpload photos={photos} max={3} label="Problem photos" optional onChange={setPhotos} onBusy={setUploading} disabled={busy}/><p className="reservation-policy">This ends your reservation, releases 1 credit and pauses the material for review. It does not mark the material as collected.</p><button className="button dark full" disabled={busy||uploading||!reason||(reason==='Other'&&!notes.trim())}>Submit report</button></form></>}
    {stage==='return-place'&&<><div className="page-heading"><h1>Return Material</h1></div><p>Put all {r.reserved_quantity} {r.unit_snapshot} of {r.name} ({r.display_code}) back in the {r.zone} Zone, with the label visible.</p><PhotoUpload photos={photos} max={3} label="Return placement photos" onChange={savePhotos} onBusy={setUploading} disabled={busy}/>{savingPhotos&&<p role="status">Saving photos…</p>}{photoError&&<div className="notice" role="alert">{photoError}<button onClick={()=>savePhotos(photos)}>Retry saving photos</button></div>}<label className="return-confirm"><input type="checkbox" checked={placed} onChange={e=>setPlaced(e.target.checked)}/>I have put all the material back in the correct place.</label><button className="button dark full spaced" disabled={busy||uploading||savingPhotos||!!photoError||!photos.length||!placed} onClick={()=>void action('return/confirm',{placed},'/me/reservations')}>Confirm return</button><p className="field-help">The server checks the 24-hour deadline again when you confirm.</p></>}
    {stage==='success'&&<section className="completion"><div className="completion-icon">✓</div><h1>Pickup completed</h1><h2>{r.name}</h2><p>{r.display_code} · {r.reserved_quantity} {r.unit_snapshot}</p><p>1 credit spent from your reservation hold.</p><Link className="button dark full flow-primary" to="/">Done</Link></section>}
    {error&&<div role="alert" className="notice">{error}</div>}
  </div>;
}
