import React, { createContext, useContext, useEffect, useState, type FormEvent, type ReactNode } from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter, Link, Navigate, NavLink, Route, Routes, useLocation, useNavigate, useSearchParams } from 'react-router-dom';
import { ArrowUpRight, ArrowRight, ArrowLeft, Search, Plus, UserRound, Compass, Leaf, Coins, MapPin, ChevronRight, Package, Clock3, LogOut, Eye, EyeOff, Heart, Bell, Layers3, Check, AlertCircle } from 'lucide-react';
import './styles.css';
import './mobile.css';
import { useI18n, messageOf, validateForm, type Message } from './i18n';

import { Auth, api, type User } from './lib';
import { MaterialDetail, MyReservations } from './reservations';
import { FulfillmentPage } from './fulfillment';
import { ProfileReviewNotice, ReviewPage } from './reviews';
import { AddInformation, DepositPage, DepositTasks, MyPosts, ShareMaterial } from './deposits';

type Material = { id:number; display_code:string; name:string; category:string; zone:string; stock_quantity:number; unit:string; dimensions_spec:string; color:string; condition:string; notes:string; image:string; is_demo:number; status:string };
type Entry = { id:number; type:string; balance_delta:number; held_delta:number; created_at:string };
function Notice({children}:{children:ReactNode}) { const {t,msg,language}=useI18n();  return <div className="notice" role="alert"><AlertCircle size={17}/><span>{children}</span></div>; }
function App() { const {t,msg,language}=useI18n(); 
  const [user,setUser] = useState<User|null>(null);
  const [loading,setLoading] = useState(true);
  const [error,setError] = useState<Message>('');
  const location = useLocation();
  useEffect(() => { api<{user:User|null}>('/auth/me').then(r=>setUser(r.user)).catch(e=>setError(messageOf(e))).finally(()=>setLoading(false)); },[]);
  useEffect(()=>{ window.scrollTo(0,0); let active=true;const refresh=()=>api<{user:User|null}>('/auth/me').then(r=>{if(active)setUser(r.user);}).catch(()=>{});void refresh();const timer=setInterval(refresh,15000);window.addEventListener('focus',refresh);return()=>{active=false;clearInterval(timer);window.removeEventListener('focus',refresh);}; },[location.pathname]);
  return <Auth.Provider value={{user,loading,setUser}}><div className="app-shell">
    <header className="site-header"><Link className="wordmark" to="/" aria-label={t("Re:Material home")}><span className="brand-mark"><Layers3 size={22}/></span>Re:Material<span className="brand-dot">®</span></Link><div className="header-right">{loading ? <span className="account-pill">{t("Loading…")}</span> : user ? <Link className="account-pill" to="/me/credits"><Coins size={16}/>{user.available} {t("credits")}</Link> : !["/login","/register"].includes(location.pathname.replace(/\/+$/,"")) ? <Link className="account-pill" to="/login">{t("Log in")}{" "}<ArrowUpRight size={15}/></Link> : null}</div></header>
    <main>{error && <Notice>{msg(error)} {t("Make sure the local server is running.")}</Notice>}<Routes>
      <Route path="/" element={<Explore/>}/><Route path="/materials" element={<Explore results/>}/><Route path="/materials/:id" element={<MaterialDetail/>}/>
      <Route path="/materials/:id/reserve" element={<MaterialDetail confirm/>}/><Route path="/reservations/:id" element={<MyReservations detail/>}/><Route path="/reservations/:id/:stage" element={<FulfillmentPage/>}/><Route path="/login" element={<AuthPage/>}/><Route path="/register" element={<AuthPage register/>}/>
      <Route path="/deposit" element={<ShareMaterial/>}/><Route path="/deposit/new" element={<AddInformation/>}/><Route path="/deposits/:id/edit" element={<AddInformation/>}/><Route path="/deposits/:id/:stage?" element={<DepositPage/>}/>
      <Route path="/me/settings" element={<Navigate to="/me" replace/>}/><Route path="/me" element={<Profile/>}/><Route path="/me/credits" element={<Credits/>}/>
      <Route path="/me/posts" element={<MyPosts/>}/><Route path="/me/issues/:id" element={<ReviewPage/>}/>
      <Route path="/me/reservations" element={<MyReservations/>}/>
      <Route path="/me/favorites" element={<Coming title={t("Favorites")} text={t("Saving materials to your account will be available with the discovery flow.")}/>}/>
      <Route path="/me/activity" element={<Activity/>}/>
      <Route path="*" element={<Coming title={t("Page not found")} text={t("This page isn’t here. Let’s find something useful.")}/>}/>
    </Routes></main>
    <nav className="bottom-nav" aria-label={t("Main navigation")}><NavLink to="/" end><Compass size={22}/><span>{t("Explore")}</span></NavLink><NavLink to="/deposit"><span className="nav-plus"><Plus size={21}/></span><span>{t("Share Material")}</span></NavLink><NavLink to="/me"><UserRound size={22}/><span>{t("Profile")}</span></NavLink></nav>
  </div></Auth.Provider>;
}
function Explore({results=false}:{results?:boolean}) { const {t,msg,language}=useI18n(); 
  const [params,setParams] = useSearchParams(); const [revision,setRevision]=useState(0);
  const [query,setQuery] = useState(params.get('q') || '');
  const [materials,setMaterials] = useState<Material[]>([]);
  const [categories,setCategories] = useState<{id:number;name:string}[]>([]);
  const [error,setError] = useState<Message>(''); const [busy,setBusy] = useState(true);
  const navigate = useNavigate(); const category = params.get('category') || '';
  useEffect(()=>{ api<{categories:{id:number;name:string}[]}>('/categories').then(r=>setCategories(r.categories)).catch(e=>setError(messageOf(e))); },[]);
  useEffect(()=>{ let active=true; setBusy(true); setMaterials([]); setError(''); api<{materials:Material[]}>(`/materials?${params.toString()}`).then(r=>{if(active)setMaterials(r.materials);}).catch(e=>{if(active)setError(messageOf(e));}).finally(()=>{if(active)setBusy(false);}); return ()=>{active=false;}; },[params,revision]);
  useEffect(()=>{const refresh=()=>setRevision(n=>n+1);const timer=setInterval(refresh,15000);window.addEventListener('focus',refresh);return()=>{clearInterval(timer);window.removeEventListener('focus',refresh);};},[]);
  useEffect(()=>setQuery(params.get('q') || ''),[params]);
  function search(e:FormEvent) { e.preventDefault(); const next=new URLSearchParams(params); if(query.trim())next.set('q',query.trim()); else next.delete('q'); navigate(`/materials?${next}`); }
  function setFilter(key:string,value:string){const next=new URLSearchParams(params);if(value)next.set(key,value);else next.delete(key);if(results)setParams(next);else navigate(`/materials?${next}`);}
  function filter(value:string) { const next=new URLSearchParams(params); if(value)next.set('category',value); else next.delete('category'); if(results)setParams(next); else navigate(`/materials?${next}`); }
  return <>
    <div className="page-heading explore-heading">{results&&<Link to="/" className="back-link"><ArrowLeft size={16}/>{t("Explore")}</Link>}<h1>{results?t("Search Results"):t("Explore materials")}</h1></div>
    <form className="search-bar" onSubmit={search}><Search size={21}/><input aria-label={t("Search materials")} placeholder="Search name, category or material code" value={query} onChange={e=>setQuery(e.target.value)}/><button type="submit" aria-label={t("Submit search")}><ArrowRight size={20}/></button></form>
    <div className="category-strip" aria-label={t("Material categories")}><button className={!category?'selected':''} onClick={()=>filter('')}>{t("All materials")}</button>{categories.map(c=><button className={category===String(c.id)?'selected':''} onClick={()=>filter(String(c.id))} key={c.id}>{t(c.name)}</button>)}</div>
    <details className="search-filters"><summary>Filters</summary><div className="filter-grid"><label>Category<select aria-label="Category" value={category} onChange={e=>setFilter('category',e.target.value)}><option value="">All categories</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Condition<select aria-label="Condition" value={params.get('condition')||''} onChange={e=>setFilter('condition',e.target.value)}><option value="">All conditions</option>{['New','Like new','Good','Used'].map(v=><option key={v}>{v}</option>)}</select></label><label>Availability<select aria-label="Availability" value={params.get('availability')||'available'} onChange={e=>setFilter('availability',e.target.value)}><option value="available">Available</option><option value="reserved">Reserved</option><option value="all">All listed materials</option></select></label></div></details>
    {!results && <DepositTasks/>}
    <section className="materials-section"><div className="section-title"><div><div className="eyebrow">{results?t("MATERIALS WITH MORE TO GIVE"):t("FRESH ON THE SHELF")}</div><h2>{results?t("Explore the possibilities"):t("Recently Added")}<span className="count">{materials.length.toString().padStart(2,'0')}</span></h2></div>{!results&&<Link to="/materials" className="text-link">{t("View all")}{" "}<ArrowUpRight size={16}/></Link>}</div>{error&&<Notice>{msg(error)} <button onClick={()=>setRevision(n=>n+1)}>Retry</button></Notice>}{busy?<div className="loading">{t("Finding materials…")}</div>:materials.length?<div className="material-grid">{materials.map(m=><MaterialCard key={m.id} material={m}/>)}</div>:!error&&<div className="empty-state"><Search/><h3>{t("No materials found")}</h3><p>{t("Try a different name or category.")}</p><button className="button outline" onClick={()=>{setQuery('');navigate('/materials');}}>{t("Clear search")}</button></div>}</section>
    {!results && <><section><div className="section-title"><div><div className="eyebrow">{t("A PLACE TO START")}</div><h2>{t("Recommended for You")}</h2></div><Leaf size={22}/></div><p className="section-description">{t("Available materials, newest on the shelf first.")}</p><div className="material-grid recommended">{materials.filter(m=>m.status==='available').slice(0,2).map(m=><MaterialCard key={m.id} material={m}/>)}</div></section></>}
    <footer className="page-footer"><Leaf size={15}/> {t("Made for making. Not for wasting.")}<span>{t("RE:MATERIAL — CAMPUS EDITION")}</span></footer>
  </>;
}
function MaterialCard({material:m}:{material:Material}) { const {t,msg,language}=useI18n();  return <Link to={`/materials/${m.id}`} className="material-card"><div className="material-image"><img src={m.image} alt={m.is_demo?m.name+" (demo placeholder)":m.name}/>{m.is_demo ? <span className="image-badge">{t("DEMO MATERIAL")}</span> : <span className="image-badge">{m.status.toUpperCase()}</span>}<span className="card-arrow"><ArrowUpRight size={18}/></span></div><div className="card-meta"><span>{t(m.category)}</span><span>{m.display_code}</span></div><h3>{m.name}</h3><div className="card-bottom"><span>{m.status==='available'?m.stock_quantity:0} {m.unit} <span className="dot-separator">·</span> {m.condition}</span><span className="credit-tag">{t("1 credit")}</span></div></Link>; }
function AuthPage({register=false}:{register?:boolean}) { const {t,msg,language}=useI18n(); 
  const {user,setUser,loading} = useContext(Auth); const navigate=useNavigate(); const [params]=useSearchParams();
  const [username,setUsername]=useState(''); const [password,setPassword]=useState(''); const [visible,setVisible]=useState(false); const [error,setError]=useState<Message>(''); const [busy,setBusy]=useState(false);
  useEffect(()=>{setError('');setPassword('');},[register]);
  async function submit(e:FormEvent) { e.preventDefault(); const validation=validateForm(e.currentTarget as HTMLFormElement); if(validation){setError(validation);return;} if(busy)return; setBusy(true);setError(''); try { const r=await api<{user:User}>(register?'/auth/register':'/auth/login',{username,password,...(register?{language}:{})}); setUser(r.user); const dest=params.get('next'); navigate(dest?.startsWith('/')&&!dest.startsWith('//')?dest:'/me',{replace:true}); } catch(e){setError(messageOf(e));}finally{setBusy(false);} }
  if(loading)return <div className="loading">{t("Loading your account…")}</div>;
  if(user)return <Coming title={`You’re logged in, ${user.username}.`} text={t("Your account is ready to go.")} link="/me" label={t("Go to Profile")}/>;
  return <div className="auth-layout"><div className="auth-intro"><div className="eyebrow">{t("WELCOME TO THE CIRCLE")}</div><h1>{register?<>{t("A little sharing.")}<br/><em>{t("A lot of possibility.")}</em></>:<>{t("Good to")}<br/><em>{t("see you again.")}</em></>}</h1><p>{t("Someone’s leftovers.")}<br/>{t("Your next great idea.")}</p><div className="auth-leaf"><Leaf size={78} strokeWidth={1}/></div></div><section className="auth-card"><span className="soft-icon"><UserRound/></span><h2>{register?t("Create an account"):t("Welcome back")}</h2><p>{register?t("Join your campus material circle."):t("Log in to pick up where you left off.")}</p>{register&&<div className="reward-note"><Coins size={19}/><span><b>{t("2 credits, on us.")}</b> {t("A one-time welcome gift.")}</span></div>}<form noValidate onSubmit={submit}><label htmlFor="username">{t("Username")}</label><input id="username" autoComplete="username" autoCapitalize="none" spellCheck={false} required minLength={3} maxLength={24} pattern="[a-zA-Z0-9_]+" value={username} onChange={e=>setUsername(e.target.value)} placeholder={t("Your username")}/>{register&&<small>{t("3–24 letters, numbers or underscores.")}</small>}<label htmlFor="password">{t("Password")}</label><div className="password-field"><input id="password" type={visible?'text':'password'} autoComplete={register?'new-password':'current-password'} required minLength={register?8:1} maxLength={128} value={password} onChange={e=>setPassword(e.target.value)} placeholder={register?t("At least 8 characters"):t("Your password")}/><button type="button" aria-label={visible?t("Hide password"):t("Show password")} onClick={()=>setVisible(!visible)}>{visible?<EyeOff size={19}/>:<Eye size={19}/>}</button></div>{error&&<Notice>{msg(error)}</Notice>}<button disabled={busy} className="button dark full" type="submit">{busy?t("Please wait…"):register?t("Create account"):t("Log in")}{!busy&&<ArrowRight size={18}/>}</button></form><p className="auth-switch">{register?t("Already part of the circle?"):t("New to Re:Material?")} <Link to={`${register?'/login':'/register'}${params.size?`?${params}`:''}`}>{register?t("Log in"):t("Create account")}</Link></p><div className="auth-fineprint">{t("Just a username and password.")}<br/>{t("No email. No phone number.")}</div></section></div>;
}
function Profile() { const {t,msg,language}=useI18n(); 
  const {user,setUser,loading}=useContext(Auth); const [busy,setBusy]=useState(false); const [error,setError]=useState<Message>(''); const navigate=useNavigate();
  if(loading)return <div className="loading">{t("Loading your profile…")}</div>;
  if(!user)return <Guest/>;
  async function logout(){setBusy(true);try{await api('/auth/logout',{});setUser(null);navigate('/login');}catch(e){setError(messageOf(e));}finally{setBusy(false);}}
  return <div className="narrow-page"><div className="page-heading"><div className="eyebrow">{t("YOUR CORNER OF THE CIRCLE")}</div><h1>{t("Profile")}</h1></div><div className="profile-person"><div className="avatar">{user.username[0].toUpperCase()}</div><div><h2>{user.username}</h2><p>{t("Here to give materials a second chapter.")}</p></div></div><div className="balance-card"><div><span>{t("Available credits")}</span><strong>{user.available.toString().padStart(2,'0')}</strong><p>{t("Ready for your next find.")}</p></div><Coins size={48} strokeWidth={1}/><div className="balance-bottom"><span>{user.held} {t("held ·")}{" "}{user.balance} {t("total")}</span><Link to="/me/credits">{t("Credit history")}{" "}<ArrowUpRight size={15}/></Link></div></div><ProfileReviewNotice/><DepositTasks/><div className="profile-links">{[{to:'posts',label:t("My Posts"),icon:<Package/>},{to:'reservations',label:t("My Reservations"),icon:<Clock3/>},{to:'favorites',label:t("Favorites"),icon:<Heart/>},{to:'activity',label:t("Activity"),icon:<Bell/>}].map(item=><Link key={item.to} to={`/me/${item.to}`}><span>{item.icon}{item.label}</span><ChevronRight size={18}/></Link>)}</div>{error&&<Notice>{msg(error)}</Notice>}<button disabled={busy} className="logout-button" onClick={logout}><LogOut size={18}/>{busy?t("Logging out…"):t("Log out")}</button></div>;
}
function Guest(){ const {t,msg,language}=useI18n(); return <div className="empty-state guest"><span className="soft-icon"><UserRound size={28}/></span><div className="eyebrow">{t("YOUR MATERIAL CIRCLE")}</div><h1>{t("Make yourself at home.")}</h1><p>{t("Keep track of your materials, pickups and credits.")}<br/>{t("Start with 2 credits when you create an account.")}</p><Link className="button dark" to="/register">{t("Create account")}{" "}<ArrowRight size={18}/></Link><Link className="text-link" to="/login">{t("Already have an account? Log in")}</Link></div>;}
function Credits() { const {t,msg,language}=useI18n(); 
  const {user,loading}=useContext(Auth); const [entries,setEntries]=useState<Entry[]>([]);const [error,setError]=useState<Message>('');
  useEffect(()=>{if(user)api<{entries:Entry[]}>('/me/credits').then(r=>setEntries(r.entries)).catch(e=>setError(messageOf(e)));},[user]);
  if(loading)return <div className="loading">{t("Loading credits…")}</div>;if(!user)return <Guest/>;
  return <div className="narrow-page"><PageHeading title={t("Credit History")}/><div className="credit-summary"><Coins size={32}/><strong>{user.available}</strong><span>{t("available credits")}</span></div><p className="section-description">{user.held} {t("held ·")}{" "}{user.balance} {t("total. Every credit has a story.")}</p>{error&&<Notice>{msg(error)}</Notice>}<div className="ledger">{entries.map(e=><div key={e.id}><span className="soft-icon"><Plus size={19}/></span><div><b>{e.type==='registration_reward'?t("Welcome credits"):e.type==='deposit_reward'?t("Material drop-off"):t(e.type.replaceAll('_',' '))}</b><p>{new Date(e.created_at).toLocaleString(language,{dateStyle:'medium',timeStyle:'short'})}</p></div><strong title={`Held credits change: ${e.held_delta}`}>{e.held_delta!==0?`${e.held_delta>0?'+':''}${e.held_delta} held / `:''}{e.balance_delta>0?'+':''}{e.balance_delta}</strong></div>)}</div></div>;
}
function Activity(){const{user,loading}=useContext(Auth);const[rows,setRows]=useState<{id:number;type:string;created_at:string}[]>([]);const[error,setError]=useState('');useEffect(()=>{if(user)api<{activities:typeof rows}>('/me/activities').then(r=>setRows(r.activities)).catch(e=>setError(e.message));},[user?.id]);if(loading)return <p className="loading">Loading activity...</p>;if(!user)return <Guest/>;return <div className="narrow-page"><PageHeading title="Activity"/>{error&&<Notice>{error}</Notice>}{rows.length?<div className="ledger">{rows.map(r=><div key={r.id}><div><b>{r.type.replaceAll('_',' ')}</b><p>{new Date(r.created_at).toLocaleString('en')}</p></div></div>)}</div>:<p>No activity yet. Material updates will appear here.</p>}</div>;}
function PageHeading({title}:{title:string}){ const {t,msg,language}=useI18n(); return <div className="page-heading"><Link to="/me" className="back-link"><ArrowLeft size={16}/> {t("Profile")}</Link><h1>{title}</h1></div>;}
function EmptyAccount({title,text,icon}:{title:string;text:string;icon:ReactNode}){ const {t,msg,language}=useI18n(); const{user,loading}=useContext(Auth);if(loading)return <div className="loading">{t("Loading…")}</div>;if(!user)return <Guest/>;return <div className="narrow-page"><PageHeading title={title}/><div className="empty-state"><span className="soft-icon">{icon}</span><h3>{t("Nothing here yet")}</h3><p>{text}</p><Link className="button outline" to="/">{t("Explore materials")}{" "}<ArrowUpRight size={16}/></Link></div></div>;}
function Coming({title,text,link='/',label='Back to Explore'}:{title:string;text:string;link?:string;label?:string}){ const {t,msg,language}=useI18n(); return <div className="empty-state coming"><span className="soft-icon"><Layers3 size={28}/></span><span className="eyebrow">{t("RE:MATERIAL")}</span><h1>{title}</h1><p>{text}</p><Link className="button dark" to={link}>{t(label)}<ArrowRight size={17}/></Link></div>;}
createRoot(document.getElementById('root')!).render(<React.StrictMode><BrowserRouter><App/></BrowserRouter></React.StrictMode>);
