import { ArrowLeft } from 'lucide-react';
import { useContext, useEffect, useRef, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { Auth, api, type User } from './lib';
import { rememberMaterial } from './recent-materials';
import { ReservationOutcome, type FulfillmentFields } from './fulfillment';
import { FavoriteButton } from './ui';

type Material = {id:number;owner_id:number;name:string;display_code:string;category:string;custom_category_name:string|null;zone:string;stock_quantity:number;available_quantity:number;unit:string;dimensions_spec:string;dimensions_not_applicable:number;condition:string;color:string;notes:string;reference_url:string|null;status:string;is_demo:number;is_favorite?:boolean;photos:{id:number;url:string}[]};
export type Reservation = FulfillmentFields & {id:number;material_id:number;name:string;display_code:string;image:string;status:string;reserved_quantity:number;unit_snapshot:string;expires_at:string;zone:string};
const label=(s:string)=>s==='reserved'?'Active':s==='unavailable'?'Needs Review':s==='closed'?'Removed / Archived':s==='issue_reported'?'Issue Reported':s.charAt(0).toUpperCase()+s.slice(1).replaceAll('_',' ');
const deadline=(s:string)=>new Date(s).toLocaleString('en',{dateStyle:'medium',timeStyle:'long'});
function ErrorBox({error}:{error:string}){return error?<div className="notice" role="alert">{error}</div>:null;}
function LoginRequired(){return <div className="empty-state"><h1>Log in to continue</h1><p>Please log in to reserve materials and view your reservations.</p><Link className="button dark" to={`/login?next=${encodeURIComponent(location.pathname)}`}>Log in</Link></div>;}
export function Remaining({expires}:{expires:string}){const[now,setNow]=useState(Date.now());useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer);},[]);const mins=Math.max(0,Math.ceil((Date.parse(expires)-now)/60000));return <span>{mins?`${Math.floor(mins/60)}h ${mins%60}m remaining`:'Reservation deadline reached'}</span>;}

export function MaterialDetail({confirm=false}:{confirm?:boolean}){
  const{id}=useParams();const{user,loading,setUser}=useContext(Auth);const navigate=useNavigate();
  const[m,setM]=useState<Material|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[quantity,setQuantity]=useState(1),[reload,setReload]=useState(0);
  const lock=useRef(false);const requestKey=useRef('');
  useEffect(()=>{if(m&&m.id===Number(id)&&!confirm&&!loading)rememberMaterial(m.id,user?.id??null);},[m?.id,id,confirm,loading,user?.id]);
  useEffect(()=>{setM(null);setError('');setQuantity(1);requestKey.current='';},[id,confirm]);
  useEffect(()=>{let active=true;const load=()=>api<{material:Material}>(`/materials/${id}`).then(r=>{if(active)setM(r.material);}).catch(e=>{if(active)setError(e.message);});void load();const timer=setInterval(load,15000);window.addEventListener('focus',load);return()=>{active=false;clearInterval(timer);window.removeEventListener('focus',load);};},[id,confirm,reload]);
  async function reserve(){if(lock.current||!m||m.is_demo)return;lock.current=true;setBusy(true);setError('');const storageKey=`reservation-request:${user?.id}:${m.id}:${quantity}`;
    try{requestKey.current=sessionStorage.getItem(storageKey)||crypto.randomUUID();sessionStorage.setItem(storageKey,requestKey.current);
      const r=await api<{reservation:Reservation}>(`/materials/${m.id}/reserve`,{quantity,request_key:requestKey.current});
      sessionStorage.removeItem(storageKey);navigate(`/reservations/${r.reservation.id}`);api<{user:User}>('/auth/me').then(a=>setUser(a.user)).catch(()=>{});
    }catch(e){setError((e as Error).message);api<{material:Material}>(`/materials/${m.id}`).then(r=>setM(r.material)).catch(()=>{});}finally{lock.current=false;setBusy(false);}}
  if(confirm&&!loading&&!user&&m&&!m.is_demo)return <LoginRequired/>;
  if(!m)return <div className="flow-page"><h1>{confirm?'Confirm Reservation':'Material Details'}</h1><ErrorBox error={error}/>{error?<button className="button outline" onClick={()=>{setError('');setReload(v=>v+1);}}>Retry</button>:<p className="loading">Loading material…</p>}</div>;
  const eligible=!m.is_demo&&m.status==='available'&&m.available_quantity>=quantity&&m.owner_id!==user?.id;
  return <div className="flow-page material-detail"><Link className="back-link" to={confirm?`/materials/${id}`:'/materials'}><ArrowLeft size={18}/>{confirm?'Material details':'Explore materials'}</Link>
    {confirm&&!m.is_demo&&<div className="page-heading"><h1>Confirm Reservation</h1></div>}
    <div className="material-gallery" tabIndex={0} aria-label="Material photos">{m.photos.map((p,i)=><img key={p.id} src={p.url} alt={`${m.name} — photo ${i+1}`}/>)}</div>{m.photos.length>1&&<p className="field-help">Swipe horizontally to view all {m.photos.length} photos.</p>}
    <div className="detail-status"><span className="status-pill">{m.is_demo?'Sample material':label(m.status)}</span>{!m.is_demo&&<span>1 credit per reservation</span>}{!confirm&&<FavoriteButton className="detail-favorite" materialId={m.id} initial={!!m.is_favorite}/>}</div>{confirm?<h2 className="detail-title">{m.name}</h2>:<h1 className="detail-title">{m.name}</h1>}
    <h2 className="spec-heading">Material information</h2><dl className="specs"><div><dt>Category</dt><dd>{m.category}{m.custom_category_name?` · ${m.custom_category_name}`:''}</dd></div><div><dt>{m.is_demo?'Example quantity':'In stock'}</dt><dd>{m.stock_quantity} {m.unit}</dd></div>{!m.is_demo&&<div><dt>Available quantity</dt><dd>{m.available_quantity} {m.unit}</dd></div>}{!confirm&&<><div><dt>Dimensions</dt><dd>{m.dimensions_not_applicable?'Not applicable':m.dimensions_spec}</dd></div><div><dt>Condition</dt><dd>{m.condition}</dd></div><div><dt>Color</dt><dd>{m.color}</dd></div></>}</dl><h2 className="spec-heading">{m.is_demo?'Sample reference':'Pickup details'}</h2><dl className="specs"><div><dt>Material code</dt><dd>{m.display_code}</dd></div><div><dt>Zone</dt><dd>{m.zone}</dd></div></dl>
    {!confirm&&<><h2>Notes</h2><p className="notes-text">{m.notes||'No additional notes.'}</p>{m.reference_url&&/^https?:\/\//i.test(m.reference_url)&&<a className="text-link spaced" href={m.reference_url} target="_blank" rel="noreferrer">Purchase / reference link ↗</a>}</>}
    {!!m.is_demo&&<p className="notice">Sample material for browsing only. This is not real Hub inventory and cannot be reserved. No credits are charged.</p>}
    {confirm&&!m.is_demo&&<><div className="material-form"><label>Quantity to collect<select value={quantity} disabled={busy} onChange={e=>setQuantity(Number(e.target.value))}>{[1,2].map(n=><option key={n} value={n} disabled={n>m.available_quantity}>{n} {m.unit}</option>)}</select></label></div><p className="reservation-policy">Held for 24 hours from confirmation. Your exact deadline appears after you confirm. 1 credit is frozen now, released if you cancel before the deadline, and spent if the reservation expires. The entire material record is reserved for you, even when you choose only 1 unit.</p><p className="field-help">Available credits: {user?.available ?? 'Loading…'}</p></>}
    <ErrorBox error={error}/>{m.owner_id===user?.id&&<p className="notice">You cannot reserve your own material.</p>}{m.status!=='available'&&<p className="notice">This material is no longer available for reservation.</p>}
    <div className="detail-actions">{m.is_demo?<><p>Sample only · unavailable for pickup</p><Link className="button outline full" to="/">Back to Explore</Link></>:<><p>Collect within 24 hours of confirmation.</p><div className="action-stack">{!user?<><p>Please log in to reserve this material.</p><Link className="button dark" to={`/login?next=/materials/${id}/reserve`}>Log in to reserve</Link></>:confirm?<><button className="button dark full" disabled={busy||!eligible} onClick={reserve}>{busy?'Reserving…':'Confirm reservation'}</button><Link className="button outline full" to={`/materials/${id}`}>Cancel</Link></>:eligible?<Link className="button dark full" to={`/materials/${id}/reserve`}>Reserve</Link>:<button className="button dark full" disabled>Reserve</button>}</div></>}</div>
  </div>;
}

export function MyReservations({detail=false}:{detail?:boolean}){
  const{id}=useParams();const{user,loading,setUser}=useContext(Auth);const[rows,setRows]=useState<Reservation[]>([]),[error,setError]=useState(''),[ready,setReady]=useState(false),[busy,setBusy]=useState<number|null>(null),[revision,setRevision]=useState(0);const lock=useRef(false);
  useEffect(()=>{if(!user)return;let active=true;setReady(false);setError('');const load=()=>api<{reservations?:Reservation[];reservation?:Reservation}>(detail?`/reservations/${id}`:'/me/reservations').then(r=>{if(active){setRows(r.reservations||[r.reservation!]);setReady(true);}}).catch(e=>{if(active){setError(e.message);setReady(true);}});void load();const timer=setInterval(load,10000);window.addEventListener('focus',load);return()=>{active=false;clearInterval(timer);window.removeEventListener('focus',load);};},[user?.id,detail,id,revision]);
  async function cancel(r:Reservation){if(lock.current)return;lock.current=true;setBusy(r.id);setError('');try{const result=await api<{reservation:Reservation}>(`/reservations/${r.id}/cancel`,{});setRows(rows=>rows.map(row=>row.id===r.id?result.reservation:row));const a=await api<{user:User}>('/auth/me');setUser(a.user);}catch(e){setError((e as Error).message);}finally{lock.current=false;setBusy(null);}}
  if(loading)return <p className="loading">Loading your account…</p>;if(!user)return <LoginRequired/>;
  return <div className={`flow-page ${detail?"reservation-detail":""}`}><Link className="back-link" to={detail?'/me/reservations':'/me'}><ArrowLeft size={18}/>{detail?'My Reservations':'Profile'}</Link><div className="page-heading"><h1>{detail?(rows[0]?.status==='reserved'?'Reservation Confirmed':'Reservation Details'):'My Reservations'}</h1></div><ErrorBox error={error}/>{error&&<button className="button outline" onClick={()=>setRevision(n=>n+1)}>Retry</button>}{!ready?<p className="loading">Loading reservations…</p>:!rows.length&&!error?<div className="empty-state"><h2>No reservations yet</h2><p>Your active, cancelled and expired reservations will appear here.</p><Link to="/" className="button dark">Explore materials</Link></div>:<div className="reservation-list">{rows.map(r=><article key={r.id} className="reservation-card"><Link className="active-task" to={detail?`/materials/${r.material_id}`:`/reservations/${r.id}`}><img src={r.image} alt={r.name}/><div><span>{r.display_code}</span><b>{r.name}</b><small>{r.reserved_quantity} {r.unit_snapshot} · {r.zone}</small></div></Link><p className="reservation-status">{label(r.status)}</p><p className="field-help">Deadline: <time dateTime={r.expires_at}>{deadline(r.expires_at)}</time></p>{r.status==='reserved'?<><p><Remaining expires={r.expires_at}/></p><p className="field-help">1 credit held. Cancel before the deadline to release it.</p><button className="button outline full" disabled={busy!==null} onClick={()=>cancel(r)}>{busy===r.id?'Cancelling…':'Cancel reservation'}</button></>:<p className="field-help">{r.status==='cancelled'?'1 credit released. The material is available again.':r.status==='expired'?'Reservation expired. 1 credit spent; the material was released.':''}</p>}<ReservationOutcome r={r}/></article>)}</div>}</div>;
}
